<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre 7 Régression logistique | Épidémiologie 2 - Labo informatique R (PTM-6675)</title>
  <meta name="description" content="Chapitre 10" />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre 7 Régression logistique | Épidémiologie 2 - Labo informatique R (PTM-6675)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Chapitre 10" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre 7 Régression logistique | Épidémiologie 2 - Labo informatique R (PTM-6675)" />
  
  <meta name="twitter:description" content="Chapitre 10" />
  

<meta name="author" content="Simon Dufour (Professeur à la Faculté de Médecine vétérinaire de l’Université de Montréal)" />


<meta name="date" content="2023-01-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="régression-linéaire.html"/>
<link rel="next" href="régression-pour-données-de-compte-et-dincidence.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Épidémiologie 2 - Labo informatique R (PTM-6675)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> À propos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#spécificités-de-r"><i class="fa fa-check"></i><b>1.1</b> Spécificités de R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html"><i class="fa fa-check"></i><b>2</b> Bonnes pratiques de gestion de projet</a>
<ul>
<li class="chapter" data-level="2.1" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#organiser-son-projet-de-recherche"><i class="fa fa-check"></i><b>2.1</b> Organiser son projet de recherche</a></li>
<li class="chapter" data-level="2.2" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#où-sauvegarder-son-projet"><i class="fa fa-check"></i><b>2.2</b> Où sauvegarder son projet</a></li>
<li class="chapter" data-level="2.3" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#où-sauvegarder-ses-données"><i class="fa fa-check"></i><b>2.3</b> Où sauvegarder ses données</a></li>
<li class="chapter" data-level="2.4" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#scripts-danalyse"><i class="fa fa-check"></i><b>2.4</b> Scripts d’analyse</a></li>
<li class="chapter" data-level="2.5" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#les-projets-r"><i class="fa fa-check"></i><b>2.5</b> Les projets R</a></li>
<li class="chapter" data-level="2.6" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#copies-de-sécurité"><i class="fa fa-check"></i><b>2.6</b> Copies de sécurité</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="obtention-des-données-pour-les-travaux-pratiques.html"><a href="obtention-des-données-pour-les-travaux-pratiques.html"><i class="fa fa-check"></i><b>3</b> Obtention des données pour les travaux pratiques</a></li>
<li class="chapter" data-level="4" data-path="aide-de-r.html"><a href="aide-de-r.html"><i class="fa fa-check"></i><b>4</b> Aide de R</a></li>
<li class="chapter" data-level="5" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>5</b> R Markdown</a></li>
<li class="chapter" data-level="6" data-path="régression-linéaire.html"><a href="régression-linéaire.html"><i class="fa fa-check"></i><b>6</b> Régression linéaire</a>
<ul>
<li class="chapter" data-level="6.1" data-path="régression-linéaire.html"><a href="régression-linéaire.html#généralités"><i class="fa fa-check"></i><b>6.1</b> Généralités</a></li>
<li class="chapter" data-level="6.2" data-path="régression-linéaire.html"><a href="régression-linéaire.html#ajouter-des-intervalles-de-confiance"><i class="fa fa-check"></i><b>6.2</b> Ajouter des intervalles de confiance</a></li>
<li class="chapter" data-level="6.3" data-path="régression-linéaire.html"><a href="régression-linéaire.html#test-de-f-pour-comparer-modèles-complet-vs.-réduit"><i class="fa fa-check"></i><b>6.3</b> Test de <em>F</em> pour comparer modèles complet <em>vs.</em> réduit</a></li>
<li class="chapter" data-level="6.4" data-path="régression-linéaire.html"><a href="régression-linéaire.html#transformer-une-variable"><i class="fa fa-check"></i><b>6.4</b> Transformer une variable</a></li>
<li class="chapter" data-level="6.5" data-path="régression-linéaire.html"><a href="régression-linéaire.html#choisir-la-valeur-de-référence-pour-une-variable-catégorique"><i class="fa fa-check"></i><b>6.5</b> Choisir la valeur de référence pour une variable catégorique</a></li>
<li class="chapter" data-level="6.6" data-path="régression-linéaire.html"><a href="régression-linéaire.html#comparer-les-niveaux-dun-prédicteur-catégorique-avec-2-catégories"><i class="fa fa-check"></i><b>6.6</b> Comparer les niveaux d’un prédicteur catégorique avec &gt;2 catégories</a></li>
<li class="chapter" data-level="6.7" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluer-une-interaction-entre-2-variables"><i class="fa fa-check"></i><b>6.7</b> Évaluer une interaction entre 2 variables</a></li>
<li class="chapter" data-level="6.8" data-path="régression-linéaire.html"><a href="régression-linéaire.html#tol-et-vif---évaluer-la-colinéarité"><i class="fa fa-check"></i><b>6.8</b> TOL et VIF - Évaluer la colinéarité</a></li>
<li class="chapter" data-level="6.9" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluation-du-modèle"><i class="fa fa-check"></i><b>6.9</b> Évaluation du modèle</a>
<ul>
<li class="chapter" data-level="6.9.1" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluer-la-linéarité-de-la-relation-à-laide-de-courbes-lissées-pour-prédicteur-quantitatif"><i class="fa fa-check"></i><b>6.9.1</b> Évaluer la linéarité de la relation à l’aide de courbes lissées (pour prédicteur quantitatif)</a></li>
<li class="chapter" data-level="6.9.2" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluer-la-linéarité-de-la-relation-à-laide-de-termes-polynomiaux-pour-prédicteur-quantitatif"><i class="fa fa-check"></i><b>6.9.2</b> Évaluer la linéarité de la relation à l’aide de termes polynomiaux (pour prédicteur quantitatif)</a></li>
<li class="chapter" data-level="6.9.3" data-path="régression-linéaire.html"><a href="régression-linéaire.html#méthodes-diagnostiques-pour-les-résiduels"><i class="fa fa-check"></i><b>6.9.3</b> Méthodes diagnostiques pour les résiduels</a></li>
<li class="chapter" data-level="6.9.4" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluation-des-observations-extrêmes-etou-influentes"><i class="fa fa-check"></i><b>6.9.4</b> Évaluation des observations extrêmes et/ou influentes</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="régression-linéaire.html"><a href="régression-linéaire.html#travaux-pratiques-1---régression-linéaire---base"><i class="fa fa-check"></i><b>6.10</b> Travaux pratiques 1 - Régression linéaire - Base</a>
<ul>
<li class="chapter" data-level="6.10.1" data-path="régression-linéaire.html"><a href="régression-linéaire.html#exercices"><i class="fa fa-check"></i><b>6.10.1</b> Exercices</a></li>
<li class="chapter" data-level="6.10.2" data-path="régression-linéaire.html"><a href="régression-linéaire.html#code-r-et-réponses"><i class="fa fa-check"></i><b>6.10.2</b> Code R et réponses</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="régression-linéaire.html"><a href="régression-linéaire.html#travaux-pratiques-2---régression-linéaire---évaluation-du-modèle"><i class="fa fa-check"></i><b>6.11</b> Travaux pratiques 2 - Régression linéaire - Évaluation du modèle</a>
<ul>
<li class="chapter" data-level="6.11.1" data-path="régression-linéaire.html"><a href="régression-linéaire.html#exercices-1"><i class="fa fa-check"></i><b>6.11.1</b> Exercices</a></li>
<li class="chapter" data-level="6.11.2" data-path="régression-linéaire.html"><a href="régression-linéaire.html#code-r-et-réponses-1"><i class="fa fa-check"></i><b>6.11.2</b> Code R et réponses</a></li>
</ul></li>
<li class="chapter" data-level="6.12" data-path="régression-linéaire.html"><a href="régression-linéaire.html#travaux-pratiques-3---régression-linéaire---construction-de-modèle"><i class="fa fa-check"></i><b>6.12</b> Travaux pratiques 3 - Régression linéaire - Construction de modèle</a>
<ul>
<li class="chapter" data-level="6.12.1" data-path="régression-linéaire.html"><a href="régression-linéaire.html#exercices-2"><i class="fa fa-check"></i><b>6.12.1</b> Exercices</a></li>
<li class="chapter" data-level="6.12.2" data-path="régression-linéaire.html"><a href="régression-linéaire.html#code-r-et-réponses-2"><i class="fa fa-check"></i><b>6.12.2</b> Code R et réponses</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="régression-logistique.html"><a href="régression-logistique.html"><i class="fa fa-check"></i><b>7</b> Régression logistique</a>
<ul>
<li class="chapter" data-level="7.1" data-path="régression-logistique.html"><a href="régression-logistique.html#généralités-1"><i class="fa fa-check"></i><b>7.1</b> Généralités</a></li>
<li class="chapter" data-level="7.2" data-path="régression-logistique.html"><a href="régression-logistique.html#effectuer-un-test-de-rapport-de-vraisemblance"><i class="fa fa-check"></i><b>7.2</b> Effectuer un test de rapport de vraisemblance</a></li>
<li class="chapter" data-level="7.3" data-path="régression-logistique.html"><a href="régression-logistique.html#ajouter-des-ic95"><i class="fa fa-check"></i><b>7.3</b> Ajouter des IC95</a></li>
<li class="chapter" data-level="7.4" data-path="régression-logistique.html"><a href="régression-logistique.html#choisir-valeur-de-référence-pour-les-variables-catégoriques"><i class="fa fa-check"></i><b>7.4</b> Choisir valeur de référence pour les variables catégoriques</a></li>
<li class="chapter" data-level="7.5" data-path="régression-logistique.html"><a href="régression-logistique.html#produire-des-tables-de-résultats"><i class="fa fa-check"></i><b>7.5</b> Produire des tables de résultats</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="régression-logistique.html"><a href="régression-logistique.html#présenter-les-rapports-de-cotes-plutôt-que-les-log-odds"><i class="fa fa-check"></i><b>7.5.1</b> Présenter les rapports de cotes plutôt que les log odds</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="régression-logistique.html"><a href="régression-logistique.html#spécifier-pour-quelle-augmentation-dun-prédicteur-continu-le-rapport-de-cotes-est-calculé"><i class="fa fa-check"></i><b>7.6</b> Spécifier pour quelle augmentation d’un prédicteur continu le rapport de cotes est calculé</a></li>
<li class="chapter" data-level="7.7" data-path="régression-logistique.html"><a href="régression-logistique.html#évaluer-une-interaction-entre-2-variables-1"><i class="fa fa-check"></i><b>7.7</b> Évaluer une interaction entre 2 variables</a></li>
<li class="chapter" data-level="7.8" data-path="régression-logistique.html"><a href="régression-logistique.html#comparer-rapports-de-cotes-pour-une-combinaison-spécifique-de-prédicteurs"><i class="fa fa-check"></i><b>7.8</b> Comparer rapports de cotes pour une combinaison spécifique de prédicteurs</a></li>
<li class="chapter" data-level="7.9" data-path="régression-logistique.html"><a href="régression-logistique.html#présenter-leffet-des-prédicteurs-sur-une-échelle-de-probabilité"><i class="fa fa-check"></i><b>7.9</b> Présenter l’effet des prédicteurs sur une échelle de probabilité</a></li>
<li class="chapter" data-level="7.10" data-path="régression-logistique.html"><a href="régression-logistique.html#linéarité-de-la-relation-pour-prédicteur-quantitatif"><i class="fa fa-check"></i><b>7.10</b> Linéarité de la relation (pour prédicteur quantitatif)</a></li>
<li class="chapter" data-level="7.11" data-path="régression-logistique.html"><a href="régression-logistique.html#test-de-fit-de-hosmer-lemeshow-et-de-pearson"><i class="fa fa-check"></i><b>7.11</b> Test de ‘fit’ de Hosmer-Lemeshow et de Pearson</a></li>
<li class="chapter" data-level="7.12" data-path="régression-logistique.html"><a href="régression-logistique.html#évaluation-des-profils-extrêmes-etou-influents"><i class="fa fa-check"></i><b>7.12</b> Évaluation des profils extrêmes et/ou influents</a></li>
<li class="chapter" data-level="7.13" data-path="régression-logistique.html"><a href="régression-logistique.html#sensibilité-spécificité-et-courbe-roc"><i class="fa fa-check"></i><b>7.13</b> Sensibilité, spécificité et courbe ROC</a></li>
<li class="chapter" data-level="7.14" data-path="régression-logistique.html"><a href="régression-logistique.html#travaux-pratiques-4---régression-logistique---base"><i class="fa fa-check"></i><b>7.14</b> Travaux pratiques 4 - Régression logistique - Base</a>
<ul>
<li class="chapter" data-level="7.14.1" data-path="régression-logistique.html"><a href="régression-logistique.html#exercices-3"><i class="fa fa-check"></i><b>7.14.1</b> Exercices</a></li>
<li class="chapter" data-level="7.14.2" data-path="régression-logistique.html"><a href="régression-logistique.html#code-r-et-réponses-3"><i class="fa fa-check"></i><b>7.14.2</b> Code R et réponses</a></li>
</ul></li>
<li class="chapter" data-level="7.15" data-path="régression-logistique.html"><a href="régression-logistique.html#travaux-pratiques-5---régression-logistique---évaluation-du-modèle"><i class="fa fa-check"></i><b>7.15</b> Travaux pratiques 5 - Régression logistique - Évaluation du modèle</a>
<ul>
<li class="chapter" data-level="7.15.1" data-path="régression-logistique.html"><a href="régression-logistique.html#exercices-4"><i class="fa fa-check"></i><b>7.15.1</b> Exercices</a></li>
<li class="chapter" data-level="7.15.2" data-path="régression-logistique.html"><a href="régression-logistique.html#code-r-et-réponses-4"><i class="fa fa-check"></i><b>7.15.2</b> Code R et réponses</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html"><i class="fa fa-check"></i><b>8</b> Régression pour données de compte et d’incidence</a>
<ul>
<li class="chapter" data-level="8.1" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#régression-de-poisson"><i class="fa fa-check"></i><b>8.1</b> Régression de Poisson</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#indiquer-un-offset-i.e.-un-dénominateur-par-exemple-un-nombre-danimal-temps-à-risque"><i class="fa fa-check"></i><b>8.1.1</b> Indiquer un “offset” (i.e., un dénominateur, par exemple un nombre d’animal-temps à risque)</a></li>
<li class="chapter" data-level="8.1.2" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#test-de-rapport-de-vraisemblance"><i class="fa fa-check"></i><b>8.1.2</b> Test de rapport de vraisemblance</a></li>
<li class="chapter" data-level="8.1.3" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#présenter-les-ratios-dincidence"><i class="fa fa-check"></i><b>8.1.3</b> Présenter les ratios d’incidence</a></li>
<li class="chapter" data-level="8.1.4" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#calculer-un-compte-prédit-dévènements"><i class="fa fa-check"></i><b>8.1.4</b> Calculer un compte prédit d’évènements</a></li>
<li class="chapter" data-level="8.1.5" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#comparer-les-niveaux-dun-prédicteur-catégorique-avec-2-catégories-1"><i class="fa fa-check"></i><b>8.1.5</b> Comparer les niveaux d’un prédicteur catégorique avec &gt; 2 catégories</a></li>
<li class="chapter" data-level="8.1.6" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#linéarité-de-la-relation-pour-prédicteur-continu"><i class="fa fa-check"></i><b>8.1.6</b> Linéarité de la relation (pour prédicteur continu)</a></li>
<li class="chapter" data-level="8.1.7" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#test-de-chi-carré-de-pearson"><i class="fa fa-check"></i><b>8.1.7</b> Test de chi-carré de Pearson</a></li>
<li class="chapter" data-level="8.1.8" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#profils-extrêmes-ou-influents"><i class="fa fa-check"></i><b>8.1.8</b> Profils extrêmes ou influents</a></li>
<li class="chapter" data-level="8.1.9" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#comparer-les-comptes-observés-et-prédits"><i class="fa fa-check"></i><b>8.1.9</b> Comparer les comptes observés et prédits</a></li>
<li class="chapter" data-level="8.1.10" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#erreurs-type-mises-à-léchelle-scaled-se"><i class="fa fa-check"></i><b>8.1.10</b> Erreurs-type mises à l’échelle (scaled SE)</a></li>
<li class="chapter" data-level="8.1.11" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#variance-robuste"><i class="fa fa-check"></i><b>8.1.11</b> Variance robuste</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#régression-binomiale-négative"><i class="fa fa-check"></i><b>8.2</b> Régression binomiale négative</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#comparer-les-modèles-poisson-et-binomial-négatif"><i class="fa fa-check"></i><b>8.2.1</b> Comparer les modèles Poisson et Binomial négatif</a></li>
<li class="chapter" data-level="8.2.2" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#évaluer-les-résiduels-dun-modèle-binomial-négatif"><i class="fa fa-check"></i><b>8.2.2</b> Évaluer les résiduels d’un modèle Binomial négatif</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#modèles-zéro-enflés"><i class="fa fa-check"></i><b>8.3</b> Modèles zéro-enflés</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#généralités-2"><i class="fa fa-check"></i><b>8.3.1</b> Généralités</a></li>
<li class="chapter" data-level="8.3.2" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#test-de-vuong-comparer-modèle-zéros-enflés-au-modèle-conventionnel"><i class="fa fa-check"></i><b>8.3.2</b> Test de Vuong – Comparer modèle zéros-enflés au modèle conventionnel</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#calcul-du-risque-relatif-à-laide-dune-régression-de-poisson"><i class="fa fa-check"></i><b>8.4</b> Calcul du risque relatif à l’aide d’une régression de Poisson</a></li>
<li class="chapter" data-level="8.5" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#travaux-pratiques-6---régression-de-poisson-et-binomiale-négative"><i class="fa fa-check"></i><b>8.5</b> Travaux pratiques 6 - Régression de Poisson et Binomiale négative</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#exercices-5"><i class="fa fa-check"></i><b>8.5.1</b> Exercices</a></li>
<li class="chapter" data-level="8.5.2" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#code-r-et-réponses-5"><i class="fa fa-check"></i><b>8.5.2</b> Code R et réponses</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#travaux-pratiques-7---modèles-modifiés-en-zéro-et-calcul-dun-risque-relatif"><i class="fa fa-check"></i><b>8.6</b> Travaux pratiques 7 - Modèles modifiés en zéro et calcul d’un risque relatif</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#exercices-6"><i class="fa fa-check"></i><b>8.6.1</b> Exercices</a></li>
<li class="chapter" data-level="8.6.2" data-path="régression-pour-données-de-compte-et-dincidence.html"><a href="régression-pour-données-de-compte-et-dincidence.html#code-r-et-réponses-6"><i class="fa fa-check"></i><b>8.6.2</b> Code R et réponses</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html"><i class="fa fa-check"></i><b>9</b> Analyses de survie</a>
<ul>
<li class="chapter" data-level="9.1" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#généralités-3"><i class="fa fa-check"></i><b>9.1</b> Généralités</a></li>
<li class="chapter" data-level="9.2" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#format-des-données-pour-une-analyse-de-survie"><i class="fa fa-check"></i><b>9.2</b> Format des données pour une analyse de survie</a></li>
<li class="chapter" data-level="9.3" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#analyses-non-paramétriques-kaplan-meier"><i class="fa fa-check"></i><b>9.3</b> Analyses non-paramétriques (Kaplan-Meier)</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#table-de-kaplan-meier-et-temps-médian-de-survie"><i class="fa fa-check"></i><b>9.3.1</b> Table de Kaplan-Meier et temps médian de survie</a></li>
<li class="chapter" data-level="9.3.2" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#courbe-de-survie-de-kaplan-meier"><i class="fa fa-check"></i><b>9.3.2</b> Courbe de survie de Kaplan-Meier</a></li>
<li class="chapter" data-level="9.3.3" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#estimer-la-probabilité-de-survie-pour-un-temps-donné"><i class="fa fa-check"></i><b>9.3.3</b> Estimer la probabilité de survie pour un temps donné</a></li>
<li class="chapter" data-level="9.3.4" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#comparaisons-entre-niveaux-dun-prédicteur-catégorique"><i class="fa fa-check"></i><b>9.3.4</b> Comparaisons entre niveaux d’un prédicteur catégorique</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#régression-de-cox-à-hasard-proportionnel"><i class="fa fa-check"></i><b>9.4</b> Régression de Cox à hasard proportionnel</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#analyses-stratifiées"><i class="fa fa-check"></i><b>9.4.1</b> Analyses stratifiées</a></li>
<li class="chapter" data-level="9.4.2" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#prédicteur-dont-la-valeur-change-dans-le-temps"><i class="fa fa-check"></i><b>9.4.2</b> Prédicteur dont la valeur change dans le temps</a></li>
<li class="chapter" data-level="9.4.3" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#prédicteur-dont-leffet-change-dans-le-temps"><i class="fa fa-check"></i><b>9.4.3</b> Prédicteur dont l’effet change dans le temps</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#évaluation-du-modèle-1"><i class="fa fa-check"></i><b>9.5</b> Évaluation du modèle</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#linéarité-de-la-relation-pour-les-prédicteurs-quantitatifs"><i class="fa fa-check"></i><b>9.5.1</b> Linéarité de la relation (pour les prédicteurs quantitatifs)</a></li>
<li class="chapter" data-level="9.5.2" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#valider-la-supposition-de-hasard-proportionnel"><i class="fa fa-check"></i><b>9.5.2</b> Valider la supposition de hasard proportionnel</a></li>
<li class="chapter" data-level="9.5.3" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#évaluer-impact-du-non-respect-de-la-supposition-de-censure-non-informative"><i class="fa fa-check"></i><b>9.5.3</b> Évaluer impact du non-respect de la supposition de censure non-informative</a></li>
<li class="chapter" data-level="9.5.4" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#observations-extrêmes"><i class="fa fa-check"></i><b>9.5.4</b> Observations extrêmes</a></li>
<li class="chapter" data-level="9.5.5" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#observations-influentes"><i class="fa fa-check"></i><b>9.5.5</b> Observations influentes</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#pour-aller-plus-loin"><i class="fa fa-check"></i><b>9.6</b> Pour aller plus loin</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#erreurs-types-robustes"><i class="fa fa-check"></i><b>9.6.1</b> Erreurs-types robustes</a></li>
<li class="chapter" data-level="9.6.2" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#régression-de-cox-à-fragilité-partagée"><i class="fa fa-check"></i><b>9.6.2</b> Régression de Cox à fragilité partagée</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#travaux-pratiques-8---analyses-de-survie-non-paramétriques"><i class="fa fa-check"></i><b>9.7</b> Travaux pratiques 8 - Analyses de survie non-paramétriques</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#exercices-7"><i class="fa fa-check"></i><b>9.7.1</b> Exercices</a></li>
<li class="chapter" data-level="9.7.2" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#code-r-et-réponses-7"><i class="fa fa-check"></i><b>9.7.2</b> Code R et réponses</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#travaux-pratiques-9---analyses-de-survie-semi-paramétriques"><i class="fa fa-check"></i><b>9.8</b> Travaux pratiques 9 - Analyses de survie semi-paramétriques</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#exercices-8"><i class="fa fa-check"></i><b>9.8.1</b> Exercices</a></li>
<li class="chapter" data-level="9.8.2" data-path="analyses-de-survie.html"><a href="analyses-de-survie.html#code-r-et-réponses-8"><i class="fa fa-check"></i><b>9.8.2</b> Code R et réponses</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html"><i class="fa fa-check"></i><b>10</b> Modèles mixtes pour données structurées</a>
<ul>
<li class="chapter" data-level="10.1" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#généralités-4"><i class="fa fa-check"></i><b>10.1</b> Généralités</a></li>
<li class="chapter" data-level="10.2" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#évaluer-la-structure-de-regroupement"><i class="fa fa-check"></i><b>10.2</b> Évaluer la structure de regroupement</a></li>
<li class="chapter" data-level="10.3" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#modèle-linéaire-mixte"><i class="fa fa-check"></i><b>10.3</b> Modèle linéaire mixte</a></li>
<li class="chapter" data-level="10.4" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#modèle-mixte-avec-un-seul-intercept-aléatoire"><i class="fa fa-check"></i><b>10.4</b> Modèle mixte avec un seul intercept aléatoire</a></li>
<li class="chapter" data-level="10.5" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#modèle-mixte-avec-plus-dun-intercept-aléatoire"><i class="fa fa-check"></i><b>10.5</b> Modèle mixte avec plus d’un intercept aléatoire</a></li>
<li class="chapter" data-level="10.6" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#partition-de-la-variance"><i class="fa fa-check"></i><b>10.6</b> Partition de la variance</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#coefficient-de-corrélation-intra-classe"><i class="fa fa-check"></i><b>10.6.1</b> Coefficient de corrélation intra-classe</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#effet-contextuel"><i class="fa fa-check"></i><b>10.7</b> Effet contextuel</a></li>
<li class="chapter" data-level="10.8" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#évaluation-du-modèle-2"><i class="fa fa-check"></i><b>10.8</b> Évaluation du modèle</a></li>
<li class="chapter" data-level="10.9" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#pentes-aléatoires"><i class="fa fa-check"></i><b>10.9</b> Pentes aléatoires</a></li>
<li class="chapter" data-level="10.10" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#travaux-pratiques-10---modèles-linéaires-mixtes"><i class="fa fa-check"></i><b>10.10</b> Travaux pratiques 10 - Modèles linéaires mixtes</a>
<ul>
<li class="chapter" data-level="10.10.1" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#exercices-9"><i class="fa fa-check"></i><b>10.10.1</b> Exercices</a></li>
<li class="chapter" data-level="10.10.2" data-path="modèles-mixtes-pour-données-structurées.html"><a href="modèles-mixtes-pour-données-structurées.html#code-r-et-réponses-9"><i class="fa fa-check"></i><b>10.10.2</b> Code R et réponses</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publié avec bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Épidémiologie 2 - Labo informatique R (PTM-6675)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="régression-logistique" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapitre 7</span> Régression logistique<a href="régression-logistique.html#régression-logistique" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="généralités-1" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Généralités<a href="régression-logistique.html#généralités-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Il existe aussi plusieurs procédures dans <code>R</code> permettant d’effectuer une régression logistique. Nous travaillerons principalement avec la fonction <code>glm()</code> qui comblera la plupart de vos besoins de ce côté. Notez que nous utiliserons cette même fonction pour d’autres types de modèles que nous verrons plus tard (e.g., Poisson, binomiale négative). Puisque la fonction <code>glm()</code> peut être utilisée pour plusieurs types de régression, il faudra donc indiquer la famille de régression qui nous intéresse, dans ce cas-ci l’argument <code>family=binomial</code> indiquera que notre variable dépendante est binomiale (i.e., elle prend seulement 2 valeurs, par exemple 0 ou 1). Dans ce cas, la fonction de lien par défaut sera la fonction logit. On aura donc une régression logistique. Notez qu’à part l’ajout de <code>family=binomial</code> la syntaxe est identique à celle de la fonction <code>lm()</code>.</p>
<p>Le jeu de donnée <em>Nocardia</em> sera utilisé pour cette section.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="régression-logistique.html#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous importons le jeu de données</span></span>
<span id="cb152-2"><a href="régression-logistique.html#cb152-2" aria-hidden="true" tabindex="-1"></a>nocardia <span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">&quot;nocardia.csv&quot;</span>, </span>
<span id="cb152-3"><a href="régression-logistique.html#cb152-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">header=</span><span class="cn">TRUE</span>, </span>
<span id="cb152-4"><a href="régression-logistique.html#cb152-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sep=</span><span class="st">&quot;;&quot;</span>)</span>
<span id="cb152-5"><a href="régression-logistique.html#cb152-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nocardia)</span></code></pre></div>
<pre><code>##   id casecont numcow prod        bscc dbarn dout dcprep dcpct dneo dclox doth
## 1  1        0     16 20,1 446,2000122     2    1      4     0    0     0    1
## 2  2        0     16 22,3         214     2    1      3   100    1     0    1
## 3  3        0     18 24,9         260     2    1      3    25    0     0    1
## 4  4        0     18      184,1999969     1    1      3     1    0     0    1
## 5  5        0     20 34,5 61,40000153     2    1      3   100    0     1    0
## 6  6        0     21 22,7 80,19999695     1    1      3     0    0     0    0</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="régression-logistique.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous indiquons les variables catégoriques dans le jeu de données</span></span>
<span id="cb154-2"><a href="régression-logistique.html#cb154-2" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dbarn <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dbarn) </span>
<span id="cb154-3"><a href="régression-logistique.html#cb154-3" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dneo <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dneo) </span>
<span id="cb154-4"><a href="régression-logistique.html#cb154-4" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dclox <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dclox) </span>
<span id="cb154-5"><a href="régression-logistique.html#cb154-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-6"><a href="régression-logistique.html#cb154-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous faisons une régression logistique</span></span>
<span id="cb154-7"><a href="régression-logistique.html#cb154-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-8"><a href="régression-logistique.html#cb154-8" aria-hidden="true" tabindex="-1"></a>modele_1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> nocardia, </span>
<span id="cb154-9"><a href="régression-logistique.html#cb154-9" aria-hidden="true" tabindex="-1"></a>                casecont <span class="sc">~</span> dcpct <span class="sc">+</span> dbarn, </span>
<span id="cb154-10"><a href="régression-logistique.html#cb154-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> binomial</span>
<span id="cb154-11"><a href="régression-logistique.html#cb154-11" aria-hidden="true" tabindex="-1"></a>                )</span>
<span id="cb154-12"><a href="régression-logistique.html#cb154-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = casecont ~ dcpct + dbarn, family = binomial, data = nocardia)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5537  -1.2441   0.1261   1.1063   1.9280  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) -1.025831   0.634461  -1.617  0.10591   
## dcpct        0.018774   0.006196   3.030  0.00244 **
## dbarn2      -0.681944   0.449586  -1.517  0.12931   
## dbarn3       0.038615   0.960075   0.040  0.96792   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 149.72  on 107  degrees of freedom
## Residual deviance: 135.49  on 104  degrees of freedom
## AIC: 143.49
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Plusieurs éléments sont présentés. D’abord, des résultats sur les résiduels de déviance (on y reviendra). Puis les coefficients, erreur-types et les résultats des tests de Wald qui permettent de tester chacun des coefficients, un à la fois (l’hypothèse nulle est que ce β=0). Notez que le résultat “Residual deviance” (135.49 avec 104 degrés de liberté) correspond au -2 log likelihood.</p>
</div>
<div id="effectuer-un-test-de-rapport-de-vraisemblance" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Effectuer un test de rapport de vraisemblance<a href="régression-logistique.html#effectuer-un-test-de-rapport-de-vraisemblance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Pour comparer le modèle complet avec le modèle nul (i.e., le modèle avec seulement un intercept) il faudra faire un test de rapport de vraisemblance (likelihood ratio test). La fonction <code>lrtest()</code> du package <code>lmtest</code> permet de réaliser ce genre de test.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="régression-logistique.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb156-2"><a href="régression-logistique.html#cb156-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(modele_1) <span class="co">#Raélise un test de rapport de vraisemblance du modèle</span></span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: casecont ~ dcpct + dbarn
## Model 2: casecont ~ 1
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)   
## 1   4 -67.747                        
## 2   1 -74.860 -3 14.225   0.002614 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Nous voyons bien les deux modèles qui sont comparés. Ici, la conclusion serait qu’au moins un des coefficients (<em>dcpct</em> ou <em>dbarn</em>) est différent de 0 (<em>P</em>=0.003).</p>
<p>Pour comparer un modèle complet <em>vs.</em> un modèle réduit, on utilisera la même fonction du même package, mais après avoir créé les deux modèles.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="régression-logistique.html#cb158-1" aria-hidden="true" tabindex="-1"></a>mod_red<span class="ot">&lt;-</span><span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb158-2"><a href="régression-logistique.html#cb158-2" aria-hidden="true" tabindex="-1"></a>             casecont<span class="sc">~</span> dcpct <span class="sc">+</span> dbarn, </span>
<span id="cb158-3"><a href="régression-logistique.html#cb158-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">family=</span><span class="st">&quot;binomial&quot;</span> </span>
<span id="cb158-4"><a href="régression-logistique.html#cb158-4" aria-hidden="true" tabindex="-1"></a>             )</span>
<span id="cb158-5"><a href="régression-logistique.html#cb158-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-6"><a href="régression-logistique.html#cb158-6" aria-hidden="true" tabindex="-1"></a>mod_comp<span class="ot">&lt;-</span><span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb158-7"><a href="régression-logistique.html#cb158-7" aria-hidden="true" tabindex="-1"></a>              casecont<span class="sc">~</span> dcpct <span class="sc">+</span> dneo <span class="sc">+</span> dclox <span class="sc">+</span> dbarn, </span>
<span id="cb158-8"><a href="régression-logistique.html#cb158-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">family=</span><span class="st">&quot;binomial&quot;</span> </span>
<span id="cb158-9"><a href="régression-logistique.html#cb158-9" aria-hidden="true" tabindex="-1"></a>              )</span>
<span id="cb158-10"><a href="régression-logistique.html#cb158-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-11"><a href="régression-logistique.html#cb158-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(mod_comp, mod_red) <span class="co">#likelihood ratio test</span></span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: casecont ~ dcpct + dneo + dclox + dbarn
## Model 2: casecont ~ dcpct + dbarn
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)    
## 1   6 -51.158                         
## 2   4 -67.747 -2 33.178  6.244e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La conclusion serait qu’au moins un des deux coefficients (<em>dneo</em> et/ou <em>dclox</em>) est différent de 0 (<em>P</em>&lt;0.001). <strong>C’est aussi à l’aide de la fonction <code>lrtest</code> qu’on pourra réaliser un test sur l’ensemble des variables indicatrices d’une variables avec &gt; 2 catégories, l’équivalent du test de <em>F</em> en régression linéaire.</strong></p>
</div>
<div id="ajouter-des-ic95" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Ajouter des IC95<a href="régression-logistique.html#ajouter-des-ic95" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vous pouvez ajouter des IC95 avec la fonction <code>confint()</code>, comme vu précédemment.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="régression-logistique.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modele_1, </span>
<span id="cb160-2"><a href="régression-logistique.html#cb160-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">level=</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                    2.5 %     97.5 %
## (Intercept) -2.354149597 0.16936727
## dcpct        0.007243426 0.03183774
## dbarn2      -1.582513404 0.19021182
## dbarn3      -1.882433338 2.00161262</code></pre>
</div>
<div id="choisir-valeur-de-référence-pour-les-variables-catégoriques" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Choisir valeur de référence pour les variables catégoriques<a href="régression-logistique.html#choisir-valeur-de-référence-pour-les-variables-catégoriques" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vous pouvez choisir les valeurs de référence pour les variables catégoriques avec la fonction <code>relevel()</code>, comme vu précédemment.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="régression-logistique.html#cb162-1" aria-hidden="true" tabindex="-1"></a>nocardia <span class="ot">&lt;-</span> <span class="fu">within</span>(nocardia, </span>
<span id="cb162-2"><a href="régression-logistique.html#cb162-2" aria-hidden="true" tabindex="-1"></a>                   dbarn<span class="ot">&lt;-</span><span class="fu">relevel</span>(dbarn, </span>
<span id="cb162-3"><a href="régression-logistique.html#cb162-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">ref=</span><span class="dv">1</span>)</span>
<span id="cb162-4"><a href="régression-logistique.html#cb162-4" aria-hidden="true" tabindex="-1"></a>                   ) <span class="co">#Dans ce cas, ça ne changera rien puisque R avait déjà pris la valeur 1 comme catégorie de référence</span></span></code></pre></div>
</div>
<div id="produire-des-tables-de-résultats" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Produire des tables de résultats<a href="régression-logistique.html#produire-des-tables-de-résultats" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Le package <code>jtools</code> vous permet de présenter des tables de résultats plus jolies:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="régression-logistique.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb163-2"><a href="régression-logistique.html#cb163-2" aria-hidden="true" tabindex="-1"></a>j <span class="ot">&lt;-</span> <span class="fu">summ</span>(modele_1, </span>
<span id="cb163-3"><a href="régression-logistique.html#cb163-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">confint =</span> <span class="cn">TRUE</span>)</span>
<span id="cb163-4"><a href="régression-logistique.html#cb163-4" aria-hidden="true" tabindex="-1"></a>j<span class="sc">$</span>coeftable</span></code></pre></div>
<pre><code>##                    Est.         2.5%      97.5%      z val.           p
## (Intercept) -1.02583119 -2.269351164 0.21768878 -1.61685557 0.105909460
## dcpct        0.01877361  0.006630146 0.03091708  3.03007440 0.002444935
## dbarn2      -0.68194417 -1.563115697 0.19922736 -1.51682840 0.129310014
## dbarn3       0.03861550 -1.843097887 1.92032888  0.04022131 0.967916686</code></pre>
<p>Ou encore, si vous utilisez <code>RMarkdown</code>.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="régression-logistique.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb165-2"><a href="régression-logistique.html#cb165-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb165-3"><a href="régression-logistique.html#cb165-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">round</span>(j<span class="sc">$</span>coeftable, </span>
<span id="cb165-4"><a href="régression-logistique.html#cb165-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">digits=</span><span class="dv">3</span>), </span>
<span id="cb165-5"><a href="régression-logistique.html#cb165-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Résultats du modèle.&quot;</span></span>
<span id="cb165-6"><a href="régression-logistique.html#cb165-6" aria-hidden="true" tabindex="-1"></a>      )<span class="sc">%&gt;%</span></span>
<span id="cb165-7"><a href="régression-logistique.html#cb165-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-47">Table 7.1: </span>Résultats du modèle.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Est.
</th>
<th style="text-align:right;">
2.5%
</th>
<th style="text-align:right;">
97.5%
</th>
<th style="text-align:right;">
z val.
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-1.026
</td>
<td style="text-align:right;">
-2.269
</td>
<td style="text-align:right;">
0.218
</td>
<td style="text-align:right;">
-1.617
</td>
<td style="text-align:right;">
0.106
</td>
</tr>
<tr>
<td style="text-align:left;">
dcpct
</td>
<td style="text-align:right;">
0.019
</td>
<td style="text-align:right;">
0.007
</td>
<td style="text-align:right;">
0.031
</td>
<td style="text-align:right;">
3.030
</td>
<td style="text-align:right;">
0.002
</td>
</tr>
<tr>
<td style="text-align:left;">
dbarn2
</td>
<td style="text-align:right;">
-0.682
</td>
<td style="text-align:right;">
-1.563
</td>
<td style="text-align:right;">
0.199
</td>
<td style="text-align:right;">
-1.517
</td>
<td style="text-align:right;">
0.129
</td>
</tr>
<tr>
<td style="text-align:left;">
dbarn3
</td>
<td style="text-align:right;">
0.039
</td>
<td style="text-align:right;">
-1.843
</td>
<td style="text-align:right;">
1.920
</td>
<td style="text-align:right;">
0.040
</td>
<td style="text-align:right;">
0.968
</td>
</tr>
</tbody>
</table>
<div id="présenter-les-rapports-de-cotes-plutôt-que-les-log-odds" class="section level3 hasAnchor" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> Présenter les rapports de cotes plutôt que les log odds<a href="régression-logistique.html#présenter-les-rapports-de-cotes-plutôt-que-les-log-odds" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Si vous désirez obtenir les rapports de cotes, alors vous pouvez simplement demander l’exposant de vos résultats comme ceci.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="régression-logistique.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous demandons de présenter les coefficients du modèle mis à l&#39;exposant</span></span>
<span id="cb166-2"><a href="régression-logistique.html#cb166-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(modele_1))</span></code></pre></div>
<pre><code>## (Intercept)       dcpct      dbarn2      dbarn3 
##   0.3584984   1.0189509   0.5056330   1.0393708</code></pre>
<p>Pour obtenir rapports de cotes et IC95 des rapports de cotes:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="régression-logistique.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ici nous avons demandé de créer une colonne représentant un vecteur de nombres (que nous avons nommé OR et qui seront les OR) et d&#39;y juxtaposer (fonction cbind) les IC95 du modèle. Il ne reste plus qu&#39;à mettre en exposant les valeurs contenues dans ces 3 colonnes pour avoir des OR et leurs IC95</span></span>
<span id="cb168-2"><a href="régression-logistique.html#cb168-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(modele_1), </span>
<span id="cb168-3"><a href="régression-logistique.html#cb168-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">confint</span>(modele_1)</span>
<span id="cb168-4"><a href="régression-logistique.html#cb168-4" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb168-5"><a href="régression-logistique.html#cb168-5" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>##                    OR      2.5 %   97.5 %
## (Intercept) 0.3584984 0.09497424 1.184555
## dcpct       1.0189509 1.00726972 1.032350
## dbarn2      0.5056330 0.20545805 1.209506
## dbarn3      1.0393708 0.15221925 7.400981</code></pre>
<p>On pourrait même arrondir, pour faire plus joli, et produire la table avec <code>RMarkdown</code>.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="régression-logistique.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb170-2"><a href="régression-logistique.html#cb170-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb170-3"><a href="régression-logistique.html#cb170-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(modele_1), </span>
<span id="cb170-4"><a href="régression-logistique.html#cb170-4" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">confint</span>(modele_1)</span>
<span id="cb170-5"><a href="régression-logistique.html#cb170-5" aria-hidden="true" tabindex="-1"></a>                      )</span>
<span id="cb170-6"><a href="régression-logistique.html#cb170-6" aria-hidden="true" tabindex="-1"></a>                ), </span>
<span id="cb170-7"><a href="régression-logistique.html#cb170-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">digits=</span><span class="dv">2</span>), </span>
<span id="cb170-8"><a href="régression-logistique.html#cb170-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Résultats du modèle.&quot;</span></span>
<span id="cb170-9"><a href="régression-logistique.html#cb170-9" aria-hidden="true" tabindex="-1"></a>      )<span class="sc">%&gt;%</span></span>
<span id="cb170-10"><a href="régression-logistique.html#cb170-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-50">Table 7.2: </span>Résultats du modèle.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
OR
</th>
<th style="text-align:right;">
2.5 %
</th>
<th style="text-align:right;">
97.5 %
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
1.18
</td>
</tr>
<tr>
<td style="text-align:left;">
dcpct
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.01
</td>
<td style="text-align:right;">
1.03
</td>
</tr>
<tr>
<td style="text-align:left;">
dbarn2
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
0.21
</td>
<td style="text-align:right;">
1.21
</td>
</tr>
<tr>
<td style="text-align:left;">
dbarn3
</td>
<td style="text-align:right;">
1.04
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:right;">
7.40
</td>
</tr>
</tbody>
</table>
<p>Dans ce cas, on voit qu’une augmentation de 1 unité de <em>dcpct</em> (le % de vaches traitées au tarissement) augmente les odds de mammite à nocardia par un facteur de 1.02 (IC95: 1.01, 1.03).</p>
</div>
</div>
<div id="spécifier-pour-quelle-augmentation-dun-prédicteur-continu-le-rapport-de-cotes-est-calculé" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Spécifier pour quelle augmentation d’un prédicteur continu le rapport de cotes est calculé<a href="régression-logistique.html#spécifier-pour-quelle-augmentation-dun-prédicteur-continu-le-rapport-de-cotes-est-calculé" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Si vous voulez produire le rapport de cotes pour une augmentation de 10 ou 20 unités de <em>dcpct</em> vous pourriez mettre à l’échelle la variable <em>dcpct</em> afin que celle-ci représente une augmentation de 10 ou 20 unités et utiliser ces nouvelles variables dans le modèle. Par exemple, pour une augmentation de 10 points de pourcentage:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="régression-logistique.html#cb171-1" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dcpct10 <span class="ot">&lt;-</span> nocardia<span class="sc">$</span>dcpct<span class="sc">/</span><span class="dv">10</span></span>
<span id="cb171-2"><a href="régression-logistique.html#cb171-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-3"><a href="régression-logistique.html#cb171-3" aria-hidden="true" tabindex="-1"></a>modele_10 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> nocardia, </span>
<span id="cb171-4"><a href="régression-logistique.html#cb171-4" aria-hidden="true" tabindex="-1"></a>                 casecont <span class="sc">~</span> dcpct10 <span class="sc">+</span> dbarn, </span>
<span id="cb171-5"><a href="régression-logistique.html#cb171-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> binomial</span>
<span id="cb171-6"><a href="régression-logistique.html#cb171-6" aria-hidden="true" tabindex="-1"></a>                 )</span>
<span id="cb171-7"><a href="régression-logistique.html#cb171-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-8"><a href="régression-logistique.html#cb171-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(modele_10),</span>
<span id="cb171-9"><a href="régression-logistique.html#cb171-9" aria-hidden="true" tabindex="-1"></a>                <span class="fu">confint</span>(modele_10)</span>
<span id="cb171-10"><a href="régression-logistique.html#cb171-10" aria-hidden="true" tabindex="-1"></a>                )</span>
<span id="cb171-11"><a href="régression-logistique.html#cb171-11" aria-hidden="true" tabindex="-1"></a>          ), </span>
<span id="cb171-12"><a href="régression-logistique.html#cb171-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##               OR 2.5 % 97.5 %
## (Intercept) 0.36  0.09   1.18
## dcpct10     1.21  1.08   1.37
## dbarn2      0.51  0.21   1.21
## dbarn3      1.04  0.15   7.40</code></pre>
<p>Donc une augmentation de 10 unités multiplie les odds de nocardia par 1.21 (IC95: 1.08, 1.37).</p>
<p>Vous auriez aussi pu simplement multiplier le coefficient et ses erreur-types par 10 et ensuite les mettre à l’exposant:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="régression-logistique.html#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Créons un objet avec les résultats du modèle</span></span>
<span id="cb173-2"><a href="régression-logistique.html#cb173-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb173-3"><a href="régression-logistique.html#cb173-3" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">summ</span>(modele_1)</span>
<span id="cb173-4"><a href="régression-logistique.html#cb173-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-5"><a href="régression-logistique.html#cb173-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Dans l&#39;objet res$coeftable la première colonne est pour les coefficents et la 2ième est pour les erreur-types. Et la 2ième rangée est pour dcpct. Le coefficient de dcpct est donc en rangée 2 et colone 1 ou res$coeftable[2,1]</span></span>
<span id="cb173-6"><a href="régression-logistique.html#cb173-6" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="dv">10</span><span class="sc">*</span>res<span class="sc">$</span>coeftable[<span class="dv">2</span>,<span class="dv">1</span>])</span>
<span id="cb173-7"><a href="régression-logistique.html#cb173-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-8"><a href="régression-logistique.html#cb173-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Et les erreur-types sont en res$coeftable[2,2]</span></span>
<span id="cb173-9"><a href="régression-logistique.html#cb173-9" aria-hidden="true" tabindex="-1"></a>L95 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="dv">10</span><span class="sc">*</span>res<span class="sc">$</span>coeftable[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">-</span><span class="fl">1.96</span><span class="sc">*</span><span class="dv">10</span><span class="sc">*</span>res<span class="sc">$</span>coeftable[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb173-10"><a href="régression-logistique.html#cb173-10" aria-hidden="true" tabindex="-1"></a>U95 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="dv">10</span><span class="sc">*</span>res<span class="sc">$</span>coeftable[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">+</span><span class="fl">1.96</span><span class="sc">*</span><span class="dv">10</span><span class="sc">*</span>res<span class="sc">$</span>coeftable[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb173-11"><a href="régression-logistique.html#cb173-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-12"><a href="régression-logistique.html#cb173-12" aria-hidden="true" tabindex="-1"></a><span class="co">#De là:</span></span>
<span id="cb173-13"><a href="régression-logistique.html#cb173-13" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">OR10=</span>OR, </span>
<span id="cb173-14"><a href="régression-logistique.html#cb173-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">LowerCI=</span>L95, </span>
<span id="cb173-15"><a href="régression-logistique.html#cb173-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">UpperCI=</span>U95), </span>
<span id="cb173-16"><a href="régression-logistique.html#cb173-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##      OR10 LowerCI UpperCI
## [1,] 1.21    1.07    1.36</code></pre>
<p>Comme vous le voyez, il y a plusieurs manières d’arriver au même résultat!</p>
</div>
<div id="évaluer-une-interaction-entre-2-variables-1" class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> Évaluer une interaction entre 2 variables<a href="régression-logistique.html#évaluer-une-interaction-entre-2-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Comme pour la fonction <code>lm()</code> vous n’avez qu’à indiquer dans votre modèle la multiplication des effets (<code>dneo</code>*<code>dclox</code>). La fonction <code>glm()</code> se chargera alors de créer toutes les variables indicatrices nécessaires.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="régression-logistique.html#cb175-1" aria-hidden="true" tabindex="-1"></a>modele_inter <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> nocardia, </span>
<span id="cb175-2"><a href="régression-logistique.html#cb175-2" aria-hidden="true" tabindex="-1"></a>                    casecont <span class="sc">~</span> dcpct <span class="sc">+</span> dneo<span class="sc">*</span>dclox, </span>
<span id="cb175-3"><a href="régression-logistique.html#cb175-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">family =</span> binomial</span>
<span id="cb175-4"><a href="régression-logistique.html#cb175-4" aria-hidden="true" tabindex="-1"></a>                    )</span>
<span id="cb175-5"><a href="régression-logistique.html#cb175-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb175-6"><a href="régression-logistique.html#cb175-6" aria-hidden="true" tabindex="-1"></a>inter <span class="ot">&lt;-</span> <span class="fu">summ</span>(modele_inter, </span>
<span id="cb175-7"><a href="régression-logistique.html#cb175-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">confint =</span> <span class="cn">TRUE</span>)</span>
<span id="cb175-8"><a href="régression-logistique.html#cb175-8" aria-hidden="true" tabindex="-1"></a>inter<span class="sc">$</span>coeftable</span></code></pre></div>
<pre><code>##                     Est.         2.5%       97.5%    z val.            p
## (Intercept)  -3.77689649 -5.723632083 -1.83016091 -3.802561 0.0001432079
## dcpct         0.02261751  0.007480181  0.03775484  2.928489 0.0034061354
## dneo1         3.18400225  1.543122188  4.82488232  3.803160 0.0001428619
## dclox1        0.44570471 -1.565269702  2.45667913  0.434399 0.6639987570
## dneo1:dclox1 -2.55199707 -4.913900617 -0.19009352 -2.117708 0.0341997943</code></pre>
</div>
<div id="comparer-rapports-de-cotes-pour-une-combinaison-spécifique-de-prédicteurs" class="section level2 hasAnchor" number="7.8">
<h2><span class="header-section-number">7.8</span> Comparer rapports de cotes pour une combinaison spécifique de prédicteurs<a href="régression-logistique.html#comparer-rapports-de-cotes-pour-une-combinaison-spécifique-de-prédicteurs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La fonction <code>pairs()</code> du package <code>emmeans</code> vous permet de comparer toutes les combinaisons possibles d’un ou plusieurs prédicteurs catégoriques et/ou quantitatifs.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="régression-logistique.html#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb177-2"><a href="régression-logistique.html#cb177-2" aria-hidden="true" tabindex="-1"></a>contrast <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(modele_inter, </span>
<span id="cb177-3"><a href="régression-logistique.html#cb177-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">c</span>(<span class="st">&quot;dneo&quot;</span>, <span class="st">&quot;dclox&quot;</span>)</span>
<span id="cb177-4"><a href="régression-logistique.html#cb177-4" aria-hidden="true" tabindex="-1"></a>                    ) </span>
<span id="cb177-5"><a href="régression-logistique.html#cb177-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(contrast)  </span></code></pre></div>
<pre><code>##  contrast                    estimate    SE  df z.ratio p.value
##  dneo0 dclox0 - dneo1 dclox0   -3.184 0.837 Inf  -3.803  0.0008
##  dneo0 dclox0 - dneo0 dclox1   -0.446 1.026 Inf  -0.434  0.9726
##  dneo0 dclox0 - dneo1 dclox1   -1.078 0.953 Inf  -1.131  0.6705
##  dneo1 dclox0 - dneo0 dclox1    2.738 0.773 Inf   3.541  0.0023
##  dneo1 dclox0 - dneo1 dclox1    2.106 0.666 Inf   3.164  0.0085
##  dneo0 dclox1 - dneo1 dclox1   -0.632 0.873 Inf  -0.724  0.8875
## 
## Results are given on the log odds ratio (not the response) scale. 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p>Rappelez-vous, si vous utilisez la fonction <code>confint()</code>sur votre fonction <code>pairs()</code>, vous aurez alors aussi les IC95.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="régression-logistique.html#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb179-2"><a href="régression-logistique.html#cb179-2" aria-hidden="true" tabindex="-1"></a>contrast <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(modele_inter, </span>
<span id="cb179-3"><a href="régression-logistique.html#cb179-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">c</span>(<span class="st">&quot;dneo&quot;</span>, <span class="st">&quot;dclox&quot;</span>)</span>
<span id="cb179-4"><a href="régression-logistique.html#cb179-4" aria-hidden="true" tabindex="-1"></a>                    ) </span>
<span id="cb179-5"><a href="régression-logistique.html#cb179-5" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">pairs</span>(contrast))  </span></code></pre></div>
<pre><code>##  contrast                    estimate    SE  df asymp.LCL asymp.UCL
##  dneo0 dclox0 - dneo1 dclox0   -3.184 0.837 Inf    -5.335     -1.03
##  dneo0 dclox0 - dneo0 dclox1   -0.446 1.026 Inf    -3.082      2.19
##  dneo0 dclox0 - dneo1 dclox1   -1.078 0.953 Inf    -3.526      1.37
##  dneo1 dclox0 - dneo0 dclox1    2.738 0.773 Inf     0.752      4.73
##  dneo1 dclox0 - dneo1 dclox1    2.106 0.666 Inf     0.396      3.82
##  dneo0 dclox1 - dneo1 dclox1   -0.632 0.873 Inf    -2.874      1.61
## 
## Results are given on the log odds ratio (not the response) scale. 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p>Nous avons maintenant tous les contrastes pour les différentes combinaisons de <em>dneo</em> et <em>dclox</em>. Par exemple, la première ligne compare ceux qui n’utilisaient aucun des deux produits (dneo0 et dclox0) <em>vs.</em> ceux qui utilisait <em>dneo</em> mais pas <em>dclox</em> (dneo1 et dclox0).</p>
<p>De là, si on voulait avoir les rapports de cotes pour les différentes comparaisons plutôt que les log odds, nous pourrions ajouter l’argument <code>type="response"</code>.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="régression-logistique.html#cb181-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">pairs</span>(contrast, </span>
<span id="cb181-2"><a href="régression-logistique.html#cb181-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb181-3"><a href="régression-logistique.html#cb181-3" aria-hidden="true" tabindex="-1"></a>        )</span></code></pre></div>
<pre><code>##  contrast                    odds.ratio      SE  df asymp.LCL asymp.UCL
##  dneo0 dclox0 / dneo1 dclox0     0.0414  0.0347 Inf   0.00482     0.356
##  dneo0 dclox0 / dneo0 dclox1     0.6404  0.6570 Inf   0.04589     8.937
##  dneo0 dclox0 / dneo1 dclox1     0.3404  0.3244 Inf   0.02942     3.939
##  dneo1 dclox0 / dneo0 dclox1    15.4606 11.9565 Inf   2.12025   112.737
##  dneo1 dclox0 / dneo1 dclox1     8.2177  5.4711 Inf   1.48575    45.452
##  dneo0 dclox1 / dneo1 dclox1     0.5315  0.4639 Inf   0.05646     5.004
## 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 4 estimates 
## Intervals are back-transformed from the log odds ratio scale</code></pre>
<p>Dans ce cas, les odds de nocardia étaient 15.5 (95CI: 2.1, 112.7) fois plus grandes pour les troupeaux utilisant seulement neomycine (1 et 0) <em>vs.</em> ceux utilisant seulement la cloxacilline (0 et 1).</p>
</div>
<div id="présenter-leffet-des-prédicteurs-sur-une-échelle-de-probabilité" class="section level2 hasAnchor" number="7.9">
<h2><span class="header-section-number">7.9</span> Présenter l’effet des prédicteurs sur une échelle de probabilité<a href="régression-logistique.html#présenter-leffet-des-prédicteurs-sur-une-échelle-de-probabilité" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Présenter vos résultats sur une échelle de probabilité (plutôt que odds ou log odds) permettra de mieux illustrer l’effet de vos différents prédicteurs. La fonction <code>plot_model()</code> du package <code>sjPlot</code>vous permet d’obtenir une telle représentation graphique de vos résultats. L’option <code>type="eff"</code> permet de rapporter les résultats sur l’échelle d’une probabilité (plutôt que odds, log odds ou OR).</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="régression-logistique.html#cb183-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb183-2"><a href="régression-logistique.html#cb183-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(modele_inter, </span>
<span id="cb183-3"><a href="régression-logistique.html#cb183-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">type=</span><span class="st">&quot;eff&quot;</span>)</span></code></pre></div>
<pre><code>## $dcpct</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-57-1"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-57-1.png" alt="Effet de différentes variables sur la probabilité de nocardia." width="672" />
<p class="caption">
Figure 7.1: Effet de différentes variables sur la probabilité de nocardia.
</p>
</div>
<pre><code>## 
## $dneo</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-57-2"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-57-2.png" alt="Effet de différentes variables sur la probabilité de nocardia." width="672" />
<p class="caption">
Figure 7.2: Effet de différentes variables sur la probabilité de nocardia.
</p>
</div>
<pre><code>## 
## $dclox</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-57-3"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-57-3.png" alt="Effet de différentes variables sur la probabilité de nocardia." width="672" />
<p class="caption">
Figure 7.3: Effet de différentes variables sur la probabilité de nocardia.
</p>
</div>
<p>On voit alors les graphiques pour chacune des variables du modèle. Par contre, souvent on voudra voir tout ensemble dans un seul graphique. On peut alors ajouter l’argument <code>terms=c("var1", "var2", "var3")</code>. La première variable apparaitra en x, la deuxième en y et la troisième séparera la figure en 2 figures.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="régression-logistique.html#cb187-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb187-2"><a href="régression-logistique.html#cb187-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(modele_inter, </span>
<span id="cb187-3"><a href="régression-logistique.html#cb187-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">type=</span><span class="st">&quot;eff&quot;</span>, </span>
<span id="cb187-4"><a href="régression-logistique.html#cb187-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">terms=</span><span class="fu">c</span>(<span class="st">&quot;dcpct&quot;</span>, <span class="st">&quot;dneo&quot;</span>, <span class="st">&quot;dclox&quot;</span>)</span>
<span id="cb187-5"><a href="régression-logistique.html#cb187-5" aria-hidden="true" tabindex="-1"></a>           )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-58"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-58-1.png" alt=" Effet de l'utilisation de la neomycine et du % de vache traitées au tarissement par niveau d'utilisation de la cloxacilline." width="672" />
<p class="caption">
Figure 7.4:  Effet de l’utilisation de la neomycine et du % de vache traitées au tarissement par niveau d’utilisation de la cloxacilline.
</p>
</div>
</div>
<div id="linéarité-de-la-relation-pour-prédicteur-quantitatif" class="section level2 hasAnchor" number="7.10">
<h2><span class="header-section-number">7.10</span> Linéarité de la relation (pour prédicteur quantitatif)<a href="régression-logistique.html#linéarité-de-la-relation-pour-prédicteur-quantitatif" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La linéarité de la relation est une supposition importante du modèle. Dans le modèle logistique, la relation entre le prédicteur et le <strong>log odds</strong> doit être une ligne droite, ce qui complique l’évaluation. Pour les prédicteurs quantitatifs, vous devrez toujours vérifier si cette supposition est bien respectée. Vous pouvez le faire, comme en régression linéaire, à l’aide du modèle polynomial (en ajoutant le <span class="math inline">\(prédicteur^2\)</span> ou le <span class="math inline">\(prédicteur^2\)</span> et le <span class="math inline">\(prédicteur^3\)</span> dans votre modèle). Si les coefficients de ces termes sont significativement différents de zéro (i.e. <em>P</em> &lt; 0.05), ont concluera que la relation est une courbe, ou une courbe avec un ou plusieurs points d’inflexion, respectivement.</p>
</div>
<div id="test-de-fit-de-hosmer-lemeshow-et-de-pearson" class="section level2 hasAnchor" number="7.11">
<h2><span class="header-section-number">7.11</span> Test de ‘fit’ de Hosmer-Lemeshow et de Pearson<a href="régression-logistique.html#test-de-fit-de-hosmer-lemeshow-et-de-pearson" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La fonction <code>hoslem.test()</code> du package <code>ResourceSelection</code> permet de réaliser le test de Hosmer-Lemeshow. Il faut simplement indiquer l’objet “modèle” avec lequel vous voulez travailler (par exemple, ici <em>modele_inter</em>). Dans cet objet, il y a toujours une variable nommée <span class="math inline">\(y\)</span> et <code>hoslem.test()</code> voudra l’utiliser, vous n’avez donc pas à modifier <em>y</em> dans le code plus bas. Il s’agit en fait de la variable réponse. Ont indique ensuite d’utiliser les valeurs prédites (<em>fitted</em>) et, encore une fois, l’objet “modèle” où elles se trouvent. Finalement on peut ou non indiquer le nombre de groupes utilisés pour le test, ici <code>g=8</code>.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="régression-logistique.html#cb188-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb188-2"><a href="régression-logistique.html#cb188-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(modele_inter<span class="sc">$</span>y, </span>
<span id="cb188-3"><a href="régression-logistique.html#cb188-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">fitted</span>(modele_inter),</span>
<span id="cb188-4"><a href="régression-logistique.html#cb188-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">g=</span><span class="dv">8</span></span>
<span id="cb188-5"><a href="régression-logistique.html#cb188-5" aria-hidden="true" tabindex="-1"></a>            )</span></code></pre></div>
<pre><code>## 
##  Hosmer and Lemeshow goodness of fit (GOF) test
## 
## data:  modele_inter$y, fitted(modele_inter)
## X-squared = 1.4887, df = 6, p-value = 0.9602</code></pre>
<p>Dans ce cas, le test ne rejette pas l’hypothèse nulle (i.e. le modèle « fit » bien les données).</p>
<p>C’est beaucoup plus demandant de réaliser les tests de fit de Déviance ou de Pearson dans R. Si vous trouvez une manière simple de le faire, indiquez-le-nous! En théorie, ont peut générer les résiduels avec la fonction <code>augment()</code> du package <code>broom</code>. Puis, la fonction <code>distinct()</code> (du package <code>dplyr</code>) pourrait être utilisée pour ne conserver que les profils uniques de prédicteurs pour un jeu de données. La fonction <code>dim()</code> permettra de rapporter le nombre de lignes dans ce jeu de données réduit (i.e., le nombre de profils). Ensuite, ont pourrait faire la somme des résiduels de Pearson de chacun de ces profils après les avoir mis au carré avec la fonction <code>sum()</code> et l’argment <code>^2</code>. La fonction <code>length()</code> permettra de calculer le nombre de coefficients dans le modèle. Puis, finalement, on cherche la probabilité d’observer cette valeur dans une table de <em>chi-carré</em> avec le nombre de degrés de liberté approprié (i.e., le nombre de profils unique - le nombre de coefficients) en utilisant la fonction <code>pchisqr()</code>. Ouf! Nous vous épargnons les détails…</p>
</div>
<div id="évaluation-des-profils-extrêmes-etou-influents" class="section level2 hasAnchor" number="7.12">
<h2><span class="header-section-number">7.12</span> Évaluation des profils extrêmes et/ou influents<a href="régression-logistique.html#évaluation-des-profils-extrêmes-etou-influents" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Comme pour la fonction <code>lm()</code>, vous pouvez demander de créer une nouvelle table contenant, en plus de vos variables originales, les différentes valeurs (e.g. résiduels de Pearson, de déviance, probabilité prédite, leviers, Delta-Beta) qui serviront à évaluer votre modèle. La fonction <code>augment()</code> du package <code>broom</code> vous permet de le faire. Vous pourrez ensuite trier cette table pour identifier, par exemple, les observations avec les résiduels, leviers ou distance de Cook les plus extrêmes et essayer de comprendre si ces observations ont quelque chose en commun.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="régression-logistique.html#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb190-2"><a href="régression-logistique.html#cb190-2" aria-hidden="true" tabindex="-1"></a>diag <span class="ot">&lt;-</span> <span class="fu">augment</span>(modele_inter) <span class="co">#Nous venons de créer une nouvelle table dans laquelle les résiduels, distance de cook, etc se trouvent maintenant</span></span>
<span id="cb190-3"><a href="régression-logistique.html#cb190-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diag)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 10
##   casecont dcpct dneo  dclox .fitted .resid .std.resid   .hat .sigma  .cooksd
##      &lt;int&gt; &lt;int&gt; &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
## 1        0     0 0     0       -3.78 -0.213     -0.215 0.0216  1.01  0.000103
## 2        0   100 1     0        1.67 -1.92      -1.94  0.0209  0.988 0.0232  
## 3        0    25 0     0       -3.21 -0.281     -0.285 0.0291  1.01  0.000248
## 4        0     1 0     0       -3.75 -0.215     -0.218 0.0218  1.01  0.000107
## 5        0   100 0     1       -1.07 -0.768     -0.803 0.0847  1.00  0.00694 
## 6        0     0 0     0       -3.78 -0.213     -0.215 0.0216  1.01  0.000103</code></pre>
<p>Notez que les valeurs prédites sont sur une échelle de log odds. Les valeurs prédites sur une échelle de probabilité ont cependant été conservées dans votre objet modèle. Vous pouvez donc simplement les ajouter à votre table de diagnostic, si vous le désirez.</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="régression-logistique.html#cb192-1" aria-hidden="true" tabindex="-1"></a>diag<span class="sc">$</span>pred_prob <span class="ot">&lt;-</span> modele_inter<span class="sc">$</span>fitted.values</span>
<span id="cb192-2"><a href="régression-logistique.html#cb192-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diag)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 11
##   casec…¹ dcpct dneo  dclox .fitted .resid .std.…²   .hat .sigma .cooksd pred_…³
##     &lt;int&gt; &lt;int&gt; &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1       0     0 0     0       -3.78 -0.213  -0.215 0.0216  1.01  1.03e-4  0.0224
## 2       0   100 1     0        1.67 -1.92   -1.94  0.0209  0.988 2.32e-2  0.841 
## 3       0    25 0     0       -3.21 -0.281  -0.285 0.0291  1.01  2.48e-4  0.0387
## 4       0     1 0     0       -3.75 -0.215  -0.218 0.0218  1.01  1.07e-4  0.0229
## 5       0   100 0     1       -1.07 -0.768  -0.803 0.0847  1.00  6.94e-3  0.256 
## 6       0     0 0     0       -3.78 -0.213  -0.215 0.0216  1.01  1.03e-4  0.0224
## # … with abbreviated variable names ¹​casecont, ²​.std.resid, ³​pred_prob</code></pre>
<p>La table suivante est un extrait des 10 premières observations de cette nouvelle table lorsque classée des résiduels de Pearson les plus grands aux plus petits. À partir de cette table, vous pourriez produire les graphiques qui vous intéresseront à l’aide de la fonction <code>ggplot()</code>.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="régression-logistique.html#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous pouvons maintenant ordonner cette table pour voir les 10 observations avec les résiduels les plus larges</span></span>
<span id="cb194-2"><a href="régression-logistique.html#cb194-2" aria-hidden="true" tabindex="-1"></a>diag_res <span class="ot">&lt;-</span> diag[<span class="fu">order</span>(<span class="sc">-</span>diag<span class="sc">$</span>.resid),]</span>
<span id="cb194-3"><a href="régression-logistique.html#cb194-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diag_res, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 11
##    casecont dcpct dneo  dclox .fitted .resid .std.resid   .hat .sigma .cooksd
##       &lt;int&gt; &lt;int&gt; &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
##  1        1    10 0     0      -3.55    2.68       2.71 0.0243  0.971  0.178 
##  2        1    50 1     1      -1.57    1.87       1.93 0.0592  0.989  0.0641
##  3        1   100 0     0      -1.52    1.85       1.94 0.0901  0.988  0.0990
##  4        1    83 0     1      -1.45    1.82       1.89 0.0707  0.989  0.0700
##  5        1   100 0     1      -1.07    1.65       1.73 0.0847  0.992  0.0589
##  6        1   100 0     1      -1.07    1.65       1.73 0.0847  0.992  0.0589
##  7        1     1 1     0      -0.570   1.43       1.50 0.0893  0.996  0.0381
##  8        1   100 1     1      -0.437   1.37       1.42 0.0757  0.997  0.0275
##  9        1   100 1     1      -0.437   1.37       1.42 0.0757  0.997  0.0275
## 10        1   100 1     1      -0.437   1.37       1.42 0.0757  0.997  0.0275
## # … with 1 more variable: pred_prob &lt;dbl&gt;</code></pre>
<p>Notez qu’une valeur prédite et un résiduel sont calculés pour chaque profil de prédicteur (et non pour chaque observation). Il est donc normal que les observations avec un profil de prédicteurs identique aient exactement les mêmes valeurs prédites et résiduels (e.g. les lignes 8, 9 et 10).</p>
</div>
<div id="sensibilité-spécificité-et-courbe-roc" class="section level2 hasAnchor" number="7.13">
<h2><span class="header-section-number">7.13</span> Sensibilité, spécificité et courbe ROC<a href="régression-logistique.html#sensibilité-spécificité-et-courbe-roc" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La fonction <code>roc()</code> de la librairie <code>pROC</code> permet de créer un nouvel objet dans lequel la sensibilité (Se) et la spécificité (Sp) sont rapportés pour tous les seuils possibles de probabilité prédite par le modèle. Pour ce, vous devrez utiliser une table dans laquelle les valeurs prédites par le modèle sont rapportées (par exemple le jeu de données créé avec la fonction <code>augment()</code> de la librairie <code>broom</code>.</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="régression-logistique.html#cb196-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Valeur prédictive du modèle</span></span>
<span id="cb196-2"><a href="régression-logistique.html#cb196-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb196-3"><a href="régression-logistique.html#cb196-3" aria-hidden="true" tabindex="-1"></a>roc_data <span class="ot">&lt;-</span> <span class="fu">roc</span>(<span class="at">data=</span>diag, </span>
<span id="cb196-4"><a href="régression-logistique.html#cb196-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">response=</span><span class="st">&quot;casecont&quot;</span>, </span>
<span id="cb196-5"><a href="régression-logistique.html#cb196-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">predictor=</span><span class="st">&quot;pred_prob&quot;</span></span>
<span id="cb196-6"><a href="régression-logistique.html#cb196-6" aria-hidden="true" tabindex="-1"></a>                )</span>
<span id="cb196-7"><a href="régression-logistique.html#cb196-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-8"><a href="régression-logistique.html#cb196-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Présenter les sensibilités et spécificités des différents seuils dans une même table.</span></span>
<span id="cb196-9"><a href="régression-logistique.html#cb196-9" aria-hidden="true" tabindex="-1"></a>accu <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">Seuil=</span>roc_data<span class="sc">$</span>thresholds, </span>
<span id="cb196-10"><a href="régression-logistique.html#cb196-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Se=</span>roc_data<span class="sc">$</span>sensitivities, </span>
<span id="cb196-11"><a href="régression-logistique.html#cb196-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Sp=</span>roc_data<span class="sc">$</span>specificities), </span>
<span id="cb196-12"><a href="régression-logistique.html#cb196-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">digits=</span><span class="dv">2</span>))</span>
<span id="cb196-13"><a href="régression-logistique.html#cb196-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-14"><a href="régression-logistique.html#cb196-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Voir la table</span></span>
<span id="cb196-15"><a href="régression-logistique.html#cb196-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb196-16"><a href="régression-logistique.html#cb196-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb196-17"><a href="régression-logistique.html#cb196-17" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(accu,  </span>
<span id="cb196-18"><a href="régression-logistique.html#cb196-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Sensibilité et spécificité du modèle pour différents seuils de probabilité prédite.&quot;</span>)<span class="sc">%&gt;%</span></span>
<span id="cb196-19"><a href="régression-logistique.html#cb196-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-63">Table 7.3: </span>Sensibilité et spécificité du modèle pour différents seuils de probabilité prédite.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Seuil
</th>
<th style="text-align:right;">
Se
</th>
<th style="text-align:right;">
Sp
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
-Inf
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.13
</td>
</tr>
<tr>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.15
</td>
</tr>
<tr>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.17
</td>
</tr>
<tr>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.17
</td>
</tr>
<tr>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.19
</td>
</tr>
<tr>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.20
</td>
</tr>
<tr>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.22
</td>
</tr>
<tr>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.24
</td>
</tr>
<tr>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
0.96
</td>
<td style="text-align:right;">
0.26
</td>
</tr>
<tr>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:right;">
0.96
</td>
<td style="text-align:right;">
0.28
</td>
</tr>
<tr>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:right;">
0.94
</td>
<td style="text-align:right;">
0.41
</td>
</tr>
<tr>
<td style="text-align:right;">
0.22
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
0.41
</td>
</tr>
<tr>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:right;">
0.57
</td>
</tr>
<tr>
<td style="text-align:right;">
0.32
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:right;">
0.59
</td>
</tr>
<tr>
<td style="text-align:right;">
0.35
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:right;">
0.61
</td>
</tr>
<tr>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.61
</td>
</tr>
<tr>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.63
</td>
</tr>
<tr>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.69
</td>
</tr>
<tr>
<td style="text-align:right;">
0.39
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.70
</td>
</tr>
<tr>
<td style="text-align:right;">
0.41
</td>
<td style="text-align:right;">
0.80
</td>
<td style="text-align:right;">
0.80
</td>
</tr>
<tr>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.80
</td>
<td style="text-align:right;">
0.81
</td>
</tr>
<tr>
<td style="text-align:right;">
0.48
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
0.83
</td>
</tr>
<tr>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
0.83
</td>
</tr>
<tr>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
0.85
</td>
</tr>
<tr>
<td style="text-align:right;">
0.60
</td>
<td style="text-align:right;">
0.74
</td>
<td style="text-align:right;">
0.85
</td>
</tr>
<tr>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
0.87
</td>
</tr>
<tr>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
0.91
</td>
</tr>
<tr>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:right;">
0.63
</td>
<td style="text-align:right;">
0.91
</td>
</tr>
<tr>
<td style="text-align:right;">
0.84
</td>
<td style="text-align:right;">
0.61
</td>
<td style="text-align:right;">
0.91
</td>
</tr>
<tr>
<td style="text-align:right;">
Inf
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1.00
</td>
</tr>
</tbody>
</table>
<p>La courbe ROC peut également être présentée de même que l’aire sous la courbe (l’AUC) à l’aide de la fonction <code>plot.roc()</code> de la librairie <code>pROC</code>.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="régression-logistique.html#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.roc</span>(roc_data, </span>
<span id="cb197-2"><a href="régression-logistique.html#cb197-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">print.auc =</span> <span class="cn">TRUE</span>, </span>
<span id="cb197-3"><a href="régression-logistique.html#cb197-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">grid =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-64"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-64-1.png" alt="Courbe ROC." width="672" />
<p class="caption">
Figure 7.5: Courbe ROC.
</p>
</div>
<p>À l’aide de la table <em>accu</em> que vous avez produite précédemment à l’aide de l’objet ROC créé, vous pourrez produire différents graphiques par exemple des graphiques illustrant comment la sensibilité (et/ou la spécificité) varie en fonction du seuil choisi.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="régression-logistique.html#cb198-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb198-2"><a href="régression-logistique.html#cb198-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb198-3"><a href="régression-logistique.html#cb198-3" aria-hidden="true" tabindex="-1"></a><span class="co">#En premier lieu, nous pouvons demander une figure du seuil de probabilité (en x) par la sensibilité (en y)</span></span>
<span id="cb198-4"><a href="régression-logistique.html#cb198-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(accu,</span>
<span id="cb198-5"><a href="régression-logistique.html#cb198-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>Seuil,</span>
<span id="cb198-6"><a href="régression-logistique.html#cb198-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">y=</span>Se)</span>
<span id="cb198-7"><a href="régression-logistique.html#cb198-7" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb198-8"><a href="régression-logistique.html#cb198-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb198-9"><a href="régression-logistique.html#cb198-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Et nous pouvons ajouter une 2e ligne (pointillée dans ce cas), pour la spécificité</span></span>
<span id="cb198-10"><a href="régression-logistique.html#cb198-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>Sp),</span>
<span id="cb198-11"><a href="régression-logistique.html#cb198-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb198-12"><a href="régression-logistique.html#cb198-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Finalement, ajuster les éléments de format de la figure</span></span>
<span id="cb198-13"><a href="régression-logistique.html#cb198-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Précision diagnostique (Se ou Sp)&quot;</span>) <span class="sc">+</span></span>
<span id="cb198-14"><a href="régression-logistique.html#cb198-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Seuil de probabilité prédite par le modèle&quot;</span>) <span class="sc">+</span></span>
<span id="cb198-15"><a href="régression-logistique.html#cb198-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-65"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-65-1.png" alt="Sensibilité (ligne continue) et spécificité (ligne pointillée) du modèle en fonction du seuil de probabilité prédite." width="672" />
<p class="caption">
Figure 7.6: Sensibilité (ligne continue) et spécificité (ligne pointillée) du modèle en fonction du seuil de probabilité prédite.
</p>
</div>
</div>
<div id="travaux-pratiques-4---régression-logistique---base" class="section level2 hasAnchor" number="7.14">
<h2><span class="header-section-number">7.14</span> Travaux pratiques 4 - Régression logistique - Base<a href="régression-logistique.html#travaux-pratiques-4---régression-logistique---base" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercices-3" class="section level3 hasAnchor" number="7.14.1">
<h3><span class="header-section-number">7.14.1</span> Exercices<a href="régression-logistique.html#exercices-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour ce TP utilisez le fichier Nocardia (voir description VER p.823).</p>
<p>Dans cette étude nous sommes intéressés à décrire la probabilité d’être un cas par rapport à un contrôle selon la proportion de vaches taries ayant reçu un traitement antibiotique ou ayant reçu de la cloxacilline, néomycine etc.</p>
<ol style="list-style-type: decimal">
<li><p>Avant de réaliser la régression logistique, on peut tout d’abord faire des tabulations croisées et calculer les rapports de cotes (RC) et tests de chi-carré pour comprendre les relations entre la variable dépendante et les prédicteurs catégoriques d’intérêt (<em>dneo</em>, <em>dclox</em> et <em>dbarn</em>). Après inspection de ces tables, quelles sont vos premières conclusions quant à la relation entre l’utilisation de cloxacilline et la probabilité de nocardiose, de même qu’entre l’utilisation de néomycine et Nocardia ?</p></li>
<li><p>Vous pourriez aussi tenter de visualiser et/ou tester comment dcpct varie en fonction du statut nocardia. Que notez-vous?</p></li>
<li><p>Vous êtes intéressé par le modèle de régression logistique suivant qui évalue l’effet d’utiliser neomycine et/ou cloxacilline sur la probabilité de Nocardia en gardant constant le type de stabulation et le % de vaches traitées (facteurs confondants).</p></li>
</ol>
<p><span class="math inline">\(logit(Pcasecont=1) = β_0 + β_1*dneo + β_2*dclox + β_3*dbarn + β_4*dcpct\)</span></p>
<p>3.1. Évaluez ce modèle à l’aide de la fonction <code>glm()</code>. Assurez-vous d’indiquer le niveau de référence 0 pour la neomycine et la cloxacilline et le niveau de référence 1 (i.e. stabulation libre) pour le type de stabulation. Quelle est la valeur de chi-carré, le nombre de degrés de liberté et la valeur de <em>P</em> du test de rapport de vraisemblance? Quelles sont vos conclusions? Quel était le test équivalent en régression linéaire?<br />
3.2. Comparez le modèle complet <em>vs.</em> un modèle sans la variable <em>dbarn</em>. Vous obtiendrez une valeur de <em>P</em> de 0.06. Dans vos tables de résultats précédentes, des valeurs de <em>P</em> de 0.03 et 0.85 sont rapportées pour dbarn 2 et dbarn 3, respectivement. Qu’indiquent ces différentes valeurs de <em>P</em> et quels étaient les tests équivalents en régression linéaire?<br />
3.3. Quels sont le coefficient et le rapport de cotes de <em>dcpct</em>? Comment les interprétez-vous?<br />
3.4. Quel serait le RC (et IC 95%) d’une augmentation de 15% de <em>dcpct</em> sur les odds de maladie?<br />
3.5. Quel est le RC de dneo ?<br />
3.6. Calculez l’IC 95% pour dneo? Comment interprétez-vous cet IC 95% et la valeur de <em>P</em> rapportée pour le test de Wald?</p>
<ol start="4" style="list-style-type: decimal">
<li>La présence d’un biais de confusion peut être vérifiée en ajoutant la variable de confusion potentielle au modèle et ensuite en décidant si le coefficient de la variable d’intérêt a changé de manière substantielle. En assumant le diagramme causal suivant :</li>
</ol>
<div class="figure">
<img src="Figures/Diag%20causal%20tp4.png" alt="" />
<p class="caption"><strong>Figure 7.8.</strong> Diagramme causal de la relation entre utilisation de la néomycine et probabilité de mammite à Nocardia.</p>
</div>
<p>Évaluez le changement relatif de l’effet de <em>dneo</em> sur la probabilité de nocardiose lorsque le modèle est ajusté ou non pour <em>dcpct</em>. Jugez-vous que ce facteur confondant cause un biais important dans cette étude?</p>
<ol start="5" style="list-style-type: decimal">
<li><p>Vous vous rappelez subitement que dans les modèles de régression, lorsque vous utilisez un prédicteur continu comme <em>dcpct</em>, celui-ci doit être linéairement associé avec votre variable dépendante (i.e. la relation est une droite).<br />
5.1. En régression logistique, c’est avec le RC ou le log odds que les variables sont linéairement associées?<br />
5.2. Vérifiez si la relation avec dcpct est linéaire. Quelles sont vos conclusions?</p></li>
<li><p>Maintenant modélisez l’interaction entre neomycine et cloxacilline dans votre modèle avec <em>dneo</em> <em>dclox</em> <em>dcpct</em> et <em>dbarn</em>.<br />
6.1. Quelles seraient les odds de nocardiose (et IC 95%) dans les troupeaux où cloxacilline et néomycine sont utilisées <em>vs.</em> ceux où aucun de ces traitements n’est utilisé? Ces troupeaux sont-ils significativement différents?<br />
6.2. Quel serait les odds de nocardiose (et IC 95%) dans les troupeaux où cloxacilline et néomycine sont utilisés vs. ceux où seulement neomycine est utilisé? Ces troupeaux sont-ils significativement différents?</p></li>
</ol>
</div>
<div id="code-r-et-réponses-3" class="section level3 hasAnchor" number="7.14.2">
<h3><span class="header-section-number">7.14.2</span> Code R et réponses<a href="régression-logistique.html#code-r-et-réponses-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour ce TP utilisez le fichier Nocardia (voir description VER p.823).</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="régression-logistique.html#cb199-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous importons ce jeu de données</span></span>
<span id="cb199-2"><a href="régression-logistique.html#cb199-2" aria-hidden="true" tabindex="-1"></a>nocardia <span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">&quot;nocardia.csv&quot;</span>, </span>
<span id="cb199-3"><a href="régression-logistique.html#cb199-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">header=</span><span class="cn">TRUE</span>, </span>
<span id="cb199-4"><a href="régression-logistique.html#cb199-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sep=</span><span class="st">&quot;;&quot;</span>)</span>
<span id="cb199-5"><a href="régression-logistique.html#cb199-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nocardia)</span></code></pre></div>
<pre><code>##   id casecont numcow prod        bscc dbarn dout dcprep dcpct dneo dclox doth
## 1  1        0     16 20,1 446,2000122     2    1      4     0    0     0    1
## 2  2        0     16 22,3         214     2    1      3   100    1     0    1
## 3  3        0     18 24,9         260     2    1      3    25    0     0    1
## 4  4        0     18      184,1999969     1    1      3     1    0     0    1
## 5  5        0     20 34,5 61,40000153     2    1      3   100    0     1    0
## 6  6        0     21 22,7 80,19999695     1    1      3     0    0     0    0</code></pre>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="régression-logistique.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous indiquons les variables catégoriques dans le jeu de données</span></span>
<span id="cb201-2"><a href="régression-logistique.html#cb201-2" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dbarn <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dbarn) </span>
<span id="cb201-3"><a href="régression-logistique.html#cb201-3" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dneo <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dneo) </span>
<span id="cb201-4"><a href="régression-logistique.html#cb201-4" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dclox <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dclox) </span>
<span id="cb201-5"><a href="régression-logistique.html#cb201-5" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>casecont <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>casecont) </span></code></pre></div>
<p>Dans cette étude nous sommes intéressés à décrire la probabilité d’être un cas par rapport à un contrôle selon la proportion de vaches taries ayant reçu un traitement antibiotique ou ayant reçu de la cloxacilline, néomycine etc.</p>
<ol style="list-style-type: decimal">
<li>Avant de réaliser la régression logistique, on peut tout d’abord faire des tabulations croisées et calculer les rapports de cotes (RC) et tests de chi-carré pour comprendre les relations entre la variable dépendante et les prédicteurs catégoriques d’intérêt (<em>dneo</em>, <em>dclox</em> et <em>dbarn</em>). Après inspection de ces tables, quelles sont vos premières conclusions quant à la relation entre l’utilisation de cloxacilline et la probabilité de nocardiose, de même qu’entre l’utilisation de néomycine et Nocardia ?</li>
</ol>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="régression-logistique.html#cb202-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Dans sjPlot la fonction tab_xtab est intéressante pour générer les table 2x2 et le test de chi-carré</span></span>
<span id="cb202-2"><a href="régression-logistique.html#cb202-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb202-3"><a href="régression-logistique.html#cb202-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Pour dneo</span></span>
<span id="cb202-4"><a href="régression-logistique.html#cb202-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_xtab</span>(<span class="at">var.row =</span> nocardia<span class="sc">$</span>dneo, </span>
<span id="cb202-5"><a href="régression-logistique.html#cb202-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">var.col =</span> nocardia<span class="sc">$</span>casecont, </span>
<span id="cb202-6"><a href="régression-logistique.html#cb202-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">&quot;dneo*casecont&quot;</span>)</span></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
dneo*casecont
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
dneo
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
casecont
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
0
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">29</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">34</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">25</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">49</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">74</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">54</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">54</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">108</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=22.707 · df=1 · φ=0.478 · p=0.000
</td>
</tr>
</table>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="régression-logistique.html#cb203-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Les valeurs dans cette table peuvent ensuite être utilisées dans epiR pour calculer les mesures d&#39;association et les chi-carré</span></span>
<span id="cb203-2"><a href="régression-logistique.html#cb203-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epiR)</span></code></pre></div>
<pre><code>## Warning: le package &#39;epiR&#39; a été compilé avec la version R 4.2.2</code></pre>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="régression-logistique.html#cb205-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">49</span>, <span class="dv">25</span>, <span class="dv">5</span>, <span class="dv">29</span>), </span>
<span id="cb205-2"><a href="régression-logistique.html#cb205-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">nrow =</span> <span class="dv">2</span>, </span>
<span id="cb205-3"><a href="régression-logistique.html#cb205-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb205-4"><a href="régression-logistique.html#cb205-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;D+&quot;</span>, <span class="st">&quot;D-&quot;</span>) </span>
<span id="cb205-5"><a href="régression-logistique.html#cb205-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;E+&quot;</span>, <span class="st">&quot;E-&quot;</span>) </span>
<span id="cb205-6"><a href="régression-logistique.html#cb205-6" aria-hidden="true" tabindex="-1"></a><span class="fu">epi.2by2</span>(<span class="at">dat =</span> <span class="fu">as.table</span>(dat), </span>
<span id="cb205-7"><a href="régression-logistique.html#cb205-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;cross.sectional&quot;</span>,</span>
<span id="cb205-8"><a href="régression-logistique.html#cb205-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf.level =</span> <span class="fl">0.95</span>, </span>
<span id="cb205-9"><a href="régression-logistique.html#cb205-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">units =</span> <span class="dv">100</span>, </span>
<span id="cb205-10"><a href="régression-logistique.html#cb205-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">outcome =</span> <span class="st">&quot;as.columns&quot;</span>)</span></code></pre></div>
<pre><code>##              Outcome +    Outcome -      Total               Prevalence *
## Exposed +           49           25         74     66.22 (54.28 to 76.81)
## Exposed -            5           29         34      14.71 (4.95 to 31.06)
## Total               54           54        108     50.00 (40.22 to 59.78)
## 
## Point estimates and 95% CIs:
## -------------------------------------------------------------------
## Prevalence ratio                               4.50 (1.97, 10.28)
## Odds ratio                                     11.37 (3.92, 32.95)
## Attrib prevalence in the exposed *             51.51 (35.45, 67.57)
## Attrib fraction in the exposed (%)            77.79 (49.29, 90.27)
## Attrib prevalence in the population *          35.29 (20.11, 50.48)
## Attrib fraction in the population (%)         70.59 (37.44, 86.17)
## -------------------------------------------------------------------
## Uncorrected chi2 test that OR = 1: chi2(1) = 24.725 Pr&gt;chi2 = &lt;0.001
## Fisher exact test that OR = 1: Pr&gt;chi2 = &lt;0.001
##  Wald confidence limits
##  CI: confidence interval
##  * Outcomes per 100 population units</code></pre>
<p><strong>Réponse:</strong> RC (IC 95%) neomycine: 11.4 (3.9, 33.0)<br />
<span class="math inline">\(X^2\)</span> : <em>P</em> &lt; 0.001<br />
Odds de Nocardia sont 11.4 fois plus élevé dans les troupeaux utilisants la néomycine.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="régression-logistique.html#cb207-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Pour dclox</span></span>
<span id="cb207-2"><a href="régression-logistique.html#cb207-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_xtab</span>(<span class="at">var.row =</span> nocardia<span class="sc">$</span>dclox, </span>
<span id="cb207-3"><a href="régression-logistique.html#cb207-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">var.col =</span> nocardia<span class="sc">$</span>casecont, </span>
<span id="cb207-4"><a href="régression-logistique.html#cb207-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">&quot;dclox*casecont&quot;</span>)</span></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
dclox*casecont
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
dclox
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
casecont
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
0
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">35</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">46</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">81</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">19</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">27</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">54</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">54</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">108</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=4.938 · df=1 · φ=0.235 · p=0.026
</td>
</tr>
</table>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="régression-logistique.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epiR)</span>
<span id="cb208-2"><a href="régression-logistique.html#cb208-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">19</span>, <span class="dv">46</span>, <span class="dv">35</span>), </span>
<span id="cb208-3"><a href="régression-logistique.html#cb208-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">nrow =</span> <span class="dv">2</span>, </span>
<span id="cb208-4"><a href="régression-logistique.html#cb208-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb208-5"><a href="régression-logistique.html#cb208-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;D+&quot;</span>, <span class="st">&quot;D-&quot;</span>) </span>
<span id="cb208-6"><a href="régression-logistique.html#cb208-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;E+&quot;</span>, <span class="st">&quot;E-&quot;</span>) </span>
<span id="cb208-7"><a href="régression-logistique.html#cb208-7" aria-hidden="true" tabindex="-1"></a><span class="fu">epi.2by2</span>(<span class="at">dat =</span> <span class="fu">as.table</span>(dat), </span>
<span id="cb208-8"><a href="régression-logistique.html#cb208-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;cross.sectional&quot;</span>,</span>
<span id="cb208-9"><a href="régression-logistique.html#cb208-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf.level =</span> <span class="fl">0.95</span>, </span>
<span id="cb208-10"><a href="régression-logistique.html#cb208-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">units =</span> <span class="dv">100</span>, </span>
<span id="cb208-11"><a href="régression-logistique.html#cb208-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">outcome =</span> <span class="st">&quot;as.columns&quot;</span>)</span></code></pre></div>
<pre><code>##              Outcome +    Outcome -      Total               Prevalence *
## Exposed +            8           19         27     29.63 (13.75 to 50.18)
## Exposed -           46           35         81     56.79 (45.31 to 67.76)
## Total               54           54        108     50.00 (40.22 to 59.78)
## 
## Point estimates and 95% CIs:
## -------------------------------------------------------------------
## Prevalence ratio                               0.52 (0.28, 0.96)
## Odds ratio                                     0.32 (0.13, 0.82)
## Attrib prevalence in the exposed *             -27.16 (-47.48, -6.84)
## Attrib fraction in the exposed (%)            -91.67 (-253.30, -3.98)
## Attrib prevalence in the population *          -6.79 (-21.12, 7.54)
## Attrib fraction in the population (%)         -13.58 (-25.64, -2.68)
## -------------------------------------------------------------------
## Uncorrected chi2 test that OR = 1: chi2(1) = 5.975 Pr&gt;chi2 = 0.015
## Fisher exact test that OR = 1: Pr&gt;chi2 = 0.025
##  Wald confidence limits
##  CI: confidence interval
##  * Outcomes per 100 population units</code></pre>
<p><strong>Réponse:</strong> RC (IC 95%) cloxacilline: 0.32 (0.13, 0.82)<br />
<span class="math inline">\(X^2\)</span> : <em>P</em> = 0.01<br />
Odds de Nocardia dans les troupeaux utilisants la cloxacilline sont multipliés par un facteur de 0.32 (i.e. odds sont plus faibles).</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="régression-logistique.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Pour dbarn</span></span>
<span id="cb210-2"><a href="régression-logistique.html#cb210-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_xtab</span>(<span class="at">var.row =</span> nocardia<span class="sc">$</span>dbarn, </span>
<span id="cb210-3"><a href="régression-logistique.html#cb210-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">var.col =</span> nocardia<span class="sc">$</span>casecont, </span>
<span id="cb210-4"><a href="régression-logistique.html#cb210-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">&quot;dbarn*casecont&quot;</span>)</span></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
dbarn*casecont
</caption>
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
dbarn
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
casecont
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">13</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">22</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">35</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
2
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">38</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">29</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">67</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
3
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">6</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">54</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">54</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">108</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">
χ<sup>2</sup>=3.523 · df=2 · Cramer’s V=0.181 · Fisher’s p=0.140
</td>
</tr>
</table>
<p><strong>Réponse:</strong> Pour <em>dbarn</em> on remarque 22 cas/35, 29 cas/67 et 3 cas/6 dans les troupeaux en stabulation entravée, libre, et autre, respectivement. Pas d’association significative (<span class="math inline">\(X^2\)</span> : <em>P</em> = 0.181).</p>
<ol start="2" style="list-style-type: decimal">
<li>Vous pourriez aussi tenter de visualiser et/ou tester comment dcpct varie en fonction du statut nocardia. Que notez-vous?</li>
</ol>
<p><strong>Réponse:</strong> Ici nous pourrions simplement faire un box-plot de <em>dcpct</em> par <em>casecont</em>.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="régression-logistique.html#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb211-2"><a href="régression-logistique.html#cb211-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>dcpct, </span>
<span id="cb211-3"><a href="régression-logistique.html#cb211-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y=</span>casecont)</span>
<span id="cb211-4"><a href="régression-logistique.html#cb211-4" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb211-5"><a href="régression-logistique.html#cb211-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb211-6"><a href="régression-logistique.html#cb211-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb211-7"><a href="régression-logistique.html#cb211-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="co">#Par défaut R produit des box-plot horizontaux, coord_flip() permet de les mettre verticaux.</span></span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-243"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-243-1.png" alt="% de vaches traitées au tarissement dans un troupeau en fonction de son statut (cas vs témoin)" width="672" />
<p class="caption">
Figure 7.7: % de vaches traitées au tarissement dans un troupeau en fonction de son statut (cas vs témoin)
</p>
</div>
<p>Nous pourrions aussi calculer la moyenne dans chacun des groupes (cas <em>vs.</em> témoin) et vérifier si cette moyenne varie en fonction du groupe. Dans le code plus bas le signe <code>%&gt;%</code> indique à <code>R</code> une séquence d’actions à faire (aussi appellé un “pipeline”). Dans ce cas nous demandons de: 1) prendre l’objet nocardia (un jeu de données); 2) grouper les observations par niveau de la variable <em>casecont</em> (group_by); 3) dans ces groupes, calculer la moyenne et la médiane de la variable <em>dcpct</em> et appeller ces valeurs “Moyenne” et “Médiane”.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="régression-logistique.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculer la moyenne par groupe:</span></span>
<span id="cb212-2"><a href="régression-logistique.html#cb212-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb212-3"><a href="régression-logistique.html#cb212-3" aria-hidden="true" tabindex="-1"></a>nocardia <span class="sc">%&gt;%</span></span>
<span id="cb212-4"><a href="régression-logistique.html#cb212-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(casecont) <span class="sc">%&gt;%</span></span>
<span id="cb212-5"><a href="régression-logistique.html#cb212-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Moyenne=</span><span class="fu">mean</span>(dcpct), </span>
<span id="cb212-6"><a href="régression-logistique.html#cb212-6" aria-hidden="true" tabindex="-1"></a>            Médiane<span class="ot">=</span><span class="fu">median</span>(dcpct))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   casecont Moyenne Médiane
##   &lt;fct&gt;      &lt;dbl&gt;   &lt;dbl&gt;
## 1 0           63.7      99
## 2 1           87.5     100</code></pre>
<p><strong>Réponse:</strong> On voit dans les figures que la majorité des troupeaux “cas” traitaient 100% des vaches alors que, pour les troupeaux “témoins”, il y avait un peu plus de troupeaux avec moins de 100% de vaches traitées. Les moyennes et médianes sont respectivement 88% et 100% pour les troupeaux cas et 64% et 99% pour les troupeaux témoins.</p>
<ol start="3" style="list-style-type: decimal">
<li>Vous êtes intéressé par le modèle de régression logistique suivant qui évalue l’effet d’utiliser neomycine et/ou cloxacilline sur la probabilité de Nocardia en gardant constant le type de stabulation et le % de vaches traitées (facteurs confondants).</li>
</ol>
<p><span class="math inline">\(logit(P de casecont=1) = β_0 + β_1*dneo + β_2*dclox + β_3*dbarn + β_4*dcpct\)</span></p>
<p>3.1. Évaluez ce modèle à l’aide de la fonction <code>glm()</code>. Assurez-vous d’indiquer le niveau de référence 0 pour la neomycine et la cloxacilline et le niveau de référence 1 (i.e. stabulation libre) pour le type de stabulation. Quelle est la valeur de chi-carré, le nombre de degrés de liberté et la valeur de <em>P</em> du test de rapport de vraisemblance? Quelles sont vos conclusions? Quel était le test équivalent en régression linéaire?</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="régression-logistique.html#cb214-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Placons d&#39;abord les niveaux de référence</span></span>
<span id="cb214-2"><a href="régression-logistique.html#cb214-2" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dneo <span class="ot">&lt;-</span> nocardia<span class="sc">$</span>dneo<span class="ot">&lt;-</span><span class="fu">relevel</span>(nocardia<span class="sc">$</span>dneo, <span class="at">ref=</span><span class="st">&quot;0&quot;</span>)</span>
<span id="cb214-3"><a href="régression-logistique.html#cb214-3" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dclox <span class="ot">&lt;-</span> nocardia<span class="sc">$</span>dclox<span class="ot">&lt;-</span><span class="fu">relevel</span>(nocardia<span class="sc">$</span>dclox, <span class="at">ref=</span><span class="st">&quot;0&quot;</span>)</span>
<span id="cb214-4"><a href="régression-logistique.html#cb214-4" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dbarn <span class="ot">&lt;-</span> nocardia<span class="sc">$</span>dbarn<span class="ot">&lt;-</span><span class="fu">relevel</span>(nocardia<span class="sc">$</span>dbarn, <span class="at">ref=</span><span class="st">&quot;1&quot;</span>)</span>
<span id="cb214-5"><a href="régression-logistique.html#cb214-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb214-6"><a href="régression-logistique.html#cb214-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Le modèle:</span></span>
<span id="cb214-7"><a href="régression-logistique.html#cb214-7" aria-hidden="true" tabindex="-1"></a>modele_1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb214-8"><a href="régression-logistique.html#cb214-8" aria-hidden="true" tabindex="-1"></a>                casecont <span class="sc">~</span> dneo <span class="sc">+</span> dclox <span class="sc">+</span> dbarn <span class="sc">+</span> dcpct, </span>
<span id="cb214-9"><a href="régression-logistique.html#cb214-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">family=</span><span class="st">&quot;binomial&quot;</span></span>
<span id="cb214-10"><a href="régression-logistique.html#cb214-10" aria-hidden="true" tabindex="-1"></a>                )</span>
<span id="cb214-11"><a href="régression-logistique.html#cb214-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb214-12"><a href="régression-logistique.html#cb214-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(modele_1)</span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: casecont ~ dneo + dclox + dbarn + dcpct
## Model 2: casecont ~ 1
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)    
## 1   6 -51.158                         
## 2   1 -74.860 -5 47.403  4.702e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Réponse:</strong> La valeur de chi-carré est 47.4 avec 5 degrés de liberté. La valeur de <em>P</em> est &lt; 0.001. Au moins un des coefficients est différent de zéro. Le test équivalent en régression linéaire est le test de <em>F</em>.</p>
<p>3.2. Comparez le modèle complet <em>vs.</em> un modèle sans la variable <em>dbarn</em>. Vous obtiendrez une valeur de <em>P</em> de 0.06. Dans vos tables de résultats précédentes, des valeurs de <em>P</em> de 0.03 et 0.85 sont rapportées pour dbarn 2 et dbarn 3, respectivement. Qu’indiquent ces différentes valeurs de <em>P</em> et quels étaient les tests équivalents en régression linéaire?</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="régression-logistique.html#cb216-1" aria-hidden="true" tabindex="-1"></a>modele_red <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb216-2"><a href="régression-logistique.html#cb216-2" aria-hidden="true" tabindex="-1"></a>                  casecont <span class="sc">~</span> dneo <span class="sc">+</span> dclox <span class="sc">+</span> dcpct, </span>
<span id="cb216-3"><a href="régression-logistique.html#cb216-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family=</span><span class="st">&quot;binomial&quot;</span></span>
<span id="cb216-4"><a href="régression-logistique.html#cb216-4" aria-hidden="true" tabindex="-1"></a>                  )</span>
<span id="cb216-5"><a href="régression-logistique.html#cb216-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(modele_1, </span>
<span id="cb216-6"><a href="régression-logistique.html#cb216-6" aria-hidden="true" tabindex="-1"></a>       modele_red)</span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: casecont ~ dneo + dclox + dbarn + dcpct
## Model 2: casecont ~ dneo + dclox + dcpct
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)  
## 1   6 -51.158                       
## 2   4 -53.994 -2 5.6707     0.0587 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="régression-logistique.html#cb218-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = casecont ~ dneo + dclox + dbarn + dcpct, family = &quot;binomial&quot;, 
##     data = nocardia)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6949  -0.7853   0.1021   0.7692   2.6801  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -2.445696   0.854328  -2.863  0.00420 ** 
## dneo1        2.685280   0.677273   3.965 7.34e-05 ***
## dclox1      -1.235266   0.580976  -2.126  0.03349 *  
## dbarn2      -1.333732   0.631925  -2.111  0.03481 *  
## dbarn3      -0.218350   1.154293  -0.189  0.84996    
## dcpct        0.021604   0.007657   2.821  0.00478 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 149.72  on 107  degrees of freedom
## Residual deviance: 102.32  on 102  degrees of freedom
## AIC: 114.32
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p><strong>Réponse:</strong> Le <em>P</em> de 0.06 indique que les coefficients des variables indicatrices utilisées pour modéliser la variable catégorique <em>dbarn</em> ne sont pas différent de zéro (i.e. globalement, <em>dbarn</em> n’est pas associé à la probabilité de nocardiose). Il s’agit d’un test de rapport de vraisemblance comparant modèles complet et réduit et ce test est équivalent au test de <em>F</em> comparant modèles complet et réduit en régression linéaire.<br />
La valeur de <em>P</em> de 0.03 indique que le coefficient de <em>dbarn2</em> (comparant cette catégorie à <em>dbarn1</em>) est différent de zéro. La valeur de <em>P</em> de 0.85 indique que le coefficient de <em>dbarn3</em> (comparant cette catégorie à <em>dbarn1</em>) n’est pas différent de zéro. Il s’agit de tests de <span class="math inline">\(X^2\)</span> de Wald et ils sont équivalents au test de <em>T</em> en régression linéaire. Normalement, on évaluerait d’abord le test global (rapport de vraissemblance) et, dans ce cas, on ne regarderait pas alors les valeurs individuelles puisque ce premier test n’est pas significatif.</p>
<p>3.3. Quels sont le coefficient et le rapport de cotes de <em>dcpct</em>? Comment les interprétez-vous?</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="régression-logistique.html#cb220-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb220-2"><a href="régression-logistique.html#cb220-2" aria-hidden="true" tabindex="-1"></a>j <span class="ot">&lt;-</span> <span class="fu">summ</span>(modele_1, </span>
<span id="cb220-3"><a href="régression-logistique.html#cb220-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">confint =</span> <span class="cn">TRUE</span>)</span>
<span id="cb220-4"><a href="régression-logistique.html#cb220-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Les coefficients:</span></span>
<span id="cb220-5"><a href="régression-logistique.html#cb220-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(j<span class="sc">$</span>coeftable, </span>
<span id="cb220-6"><a href="régression-logistique.html#cb220-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits=</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>##               Est.   2.5%  97.5% z val.     p
## (Intercept) -2.446 -4.120 -0.771 -2.863 0.004
## dneo1        2.685  1.358  4.013  3.965 0.000
## dclox1      -1.235 -2.374 -0.097 -2.126 0.033
## dbarn2      -1.334 -2.572 -0.095 -2.111 0.035
## dbarn3      -0.218 -2.481  2.044 -0.189 0.850
## dcpct        0.022  0.007  0.037  2.821 0.005</code></pre>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="régression-logistique.html#cb222-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Les rapports de cotes:</span></span>
<span id="cb222-2"><a href="régression-logistique.html#cb222-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(j<span class="sc">$</span>coeftable),</span>
<span id="cb222-3"><a href="régression-logistique.html#cb222-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##              Est. 2.5% 97.5% z val.    p
## (Intercept)  0.09 0.02  0.46   0.06 1.00
## dneo1       14.66 3.89 55.30  52.71 1.00
## dclox1       0.29 0.09  0.91   0.12 1.03
## dbarn2       0.26 0.08  0.91   0.12 1.04
## dbarn3       0.80 0.08  7.72   0.83 2.34
## dcpct        1.02 1.01  1.04  16.80 1.00</code></pre>
<p><strong>Réponse:</strong> Coefficient=0.022; le log odds d’être malade augmente de 0.022 unité par augmentation d’une unité (i.e. de 1%) du nombre de vaches traitées.<br />
RC=1.02; les odds de nocardia sont multipliées par 1.02 (l’exposant de 0.022) par augmentation d’une unité (i.e. de 1%) du nombre de vaches traitées.</p>
<p>3.4. Quel serait le RC (et IC 95%) d’une augmentation de 15% de <em>dcpct</em> sur les odds de maladie?</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="régression-logistique.html#cb224-1" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dcpct15 <span class="ot">&lt;-</span> nocardia<span class="sc">$</span>dcpct<span class="sc">/</span><span class="dv">15</span></span>
<span id="cb224-2"><a href="régression-logistique.html#cb224-2" aria-hidden="true" tabindex="-1"></a>modele15 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb224-3"><a href="régression-logistique.html#cb224-3" aria-hidden="true" tabindex="-1"></a>                casecont <span class="sc">~</span> dneo <span class="sc">+</span> dclox <span class="sc">+</span> dbarn <span class="sc">+</span> dcpct15, </span>
<span id="cb224-4"><a href="régression-logistique.html#cb224-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">family=</span><span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb224-5"><a href="régression-logistique.html#cb224-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb224-6"><a href="régression-logistique.html#cb224-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb224-7"><a href="régression-logistique.html#cb224-7" aria-hidden="true" tabindex="-1"></a>j <span class="ot">&lt;-</span> <span class="fu">summ</span>(modele15, </span>
<span id="cb224-8"><a href="régression-logistique.html#cb224-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">confint =</span> <span class="cn">TRUE</span>)</span>
<span id="cb224-9"><a href="régression-logistique.html#cb224-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Les rapports de cotes:</span></span>
<span id="cb224-10"><a href="régression-logistique.html#cb224-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(j<span class="sc">$</span>coeftable), </span>
<span id="cb224-11"><a href="régression-logistique.html#cb224-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##              Est. 2.5% 97.5% z val.    p
## (Intercept)  0.09 0.02  0.46   0.06 1.00
## dneo1       14.66 3.89 55.30  52.71 1.00
## dclox1       0.29 0.09  0.91   0.12 1.03
## dbarn2       0.26 0.08  0.91   0.12 1.04
## dbarn3       0.80 0.08  7.72   0.83 2.34
## dcpct15      1.38 1.10  1.73  16.80 1.00</code></pre>
<p><strong>Réponse:</strong> RC (IC95): 1.38 (1.10, 1.73)</p>
<p>3.5. Quel est le RC de dneo ?<br />
<strong>Réponse:</strong> RC: 14.66</p>
<p>3.6. Calculez l’IC 95% pour dneo? Comment interprétez-vous cet IC 95% et la valeur de <em>P</em> rapportée pour le test de Wald?<br />
<strong>Réponse:</strong> IC95: (3.89, 55.30). L’IC 95% indique que le RC de <em>dneo</em> est différent de 1 (i.e. l’utilisation de néomycine est associée statistiquement à la probabilité de nocardiose). Le test de <span class="math inline">\(X^2\)</span> de Wald indique que le coefficient de régression de <em>dneo</em> est différent de zéro (i.e. l’utilisation de néomycine est associée statistiquement à la probabilité de nocardiose).</p>
<ol start="4" style="list-style-type: decimal">
<li>La présence d’un biais de confusion peut être vérifiée en ajoutant la variable de confusion potentielle au modèle et ensuite en décidant si le coefficient de la variable d’intérêt a changé de manière substantielle. En assumant le diagramme causal suivant :</li>
</ol>
<div class="figure">
<img src="Figures/Diag%20causal%20tp4.png" alt="" />
<p class="caption"><strong>Figure 7.6.</strong> Diagramme causal de la relation entre utilisation de la néomycine et probabilité de mammite à Nocardia.</p>
</div>
<p>Évaluez le changement relatif de l’effet de <em>dneo</em> sur la probabilité de nocardiose lorsque le modèle est ajusté ou non pour <em>dcpct</em>. Jugez-vous que ce facteur confondant cause un biais important dans cette étude?</p>
<p>Sur l’échelle log odds:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="régression-logistique.html#cb226-1" aria-hidden="true" tabindex="-1"></a>modele_incond <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb226-2"><a href="régression-logistique.html#cb226-2" aria-hidden="true" tabindex="-1"></a>                     casecont <span class="sc">~</span> dneo, </span>
<span id="cb226-3"><a href="régression-logistique.html#cb226-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family=</span><span class="st">&quot;binomial&quot;</span></span>
<span id="cb226-4"><a href="régression-logistique.html#cb226-4" aria-hidden="true" tabindex="-1"></a>                     )</span>
<span id="cb226-5"><a href="régression-logistique.html#cb226-5" aria-hidden="true" tabindex="-1"></a>modele_cond_dcpct <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb226-6"><a href="régression-logistique.html#cb226-6" aria-hidden="true" tabindex="-1"></a>                         casecont <span class="sc">~</span> dneo <span class="sc">+</span> dcpct, </span>
<span id="cb226-7"><a href="régression-logistique.html#cb226-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">family=</span><span class="st">&quot;binomial&quot;</span></span>
<span id="cb226-8"><a href="régression-logistique.html#cb226-8" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb226-9"><a href="régression-logistique.html#cb226-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb226-10"><a href="régression-logistique.html#cb226-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculer différence relative sur l&#39;échelle log odd</span></span>
<span id="cb226-11"><a href="régression-logistique.html#cb226-11" aria-hidden="true" tabindex="-1"></a>diff <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span>(modele_incond<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">-</span>modele_cond_dcpct<span class="sc">$</span>coefficients[<span class="dv">2</span>])<span class="sc">/</span>modele_incond<span class="sc">$</span>coefficients[<span class="dv">2</span>],</span>
<span id="cb226-12"><a href="régression-logistique.html#cb226-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">digits=</span><span class="dv">1</span>)</span>
<span id="cb226-13"><a href="régression-logistique.html#cb226-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Créer une table avec log odds inconditionnelle, conditionnelle et diff relative </span></span>
<span id="cb226-14"><a href="régression-logistique.html#cb226-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">inconditionnelle=</span>modele_incond<span class="sc">$</span>coefficients[<span class="dv">2</span>], </span>
<span id="cb226-15"><a href="régression-logistique.html#cb226-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">conditionnelle=</span>modele_cond_dcpct<span class="sc">$</span>coefficients[<span class="dv">2</span>], </span>
<span id="cb226-16"><a href="régression-logistique.html#cb226-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">Difference_relative=</span>diff)</span></code></pre></div>
<pre><code>##       inconditionnelle conditionnelle Difference_relative
## dneo1         2.430802       2.400661                 1.2</code></pre>
<p>Sur l’échelle RC:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="régression-logistique.html#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculer différence relative sur l&#39;échelle RC</span></span>
<span id="cb228-2"><a href="régression-logistique.html#cb228-2" aria-hidden="true" tabindex="-1"></a>diff <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span>((<span class="fu">exp</span>(modele_incond<span class="sc">$</span>coefficients[<span class="dv">2</span>])<span class="sc">-</span><span class="fu">exp</span>(modele_cond_dcpct<span class="sc">$</span>coefficients[<span class="dv">2</span>]))<span class="sc">/</span><span class="fu">exp</span>(modele_incond<span class="sc">$</span>coefficients[<span class="dv">2</span>])), </span>
<span id="cb228-3"><a href="régression-logistique.html#cb228-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">digits=</span><span class="dv">2</span>)</span>
<span id="cb228-4"><a href="régression-logistique.html#cb228-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Créer une table avec log odds de l&#39;analyse inconditionnelle, conditionnelle et la diff relative </span></span>
<span id="cb228-5"><a href="régression-logistique.html#cb228-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">inconditionnelle=</span><span class="fu">exp</span>(modele_incond<span class="sc">$</span>coefficients[<span class="dv">2</span>]), </span>
<span id="cb228-6"><a href="régression-logistique.html#cb228-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">conditionnelle=</span><span class="fu">exp</span>(modele_cond_dcpct<span class="sc">$</span>coefficients[<span class="dv">2</span>]), </span>
<span id="cb228-7"><a href="régression-logistique.html#cb228-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">Difference_relative=</span>diff)</span></code></pre></div>
<pre><code>##       inconditionnelle conditionnelle Difference_relative
## dneo1           11.368       11.03047                2.97</code></pre>
<p><strong>Réponse:</strong> D’une manière ou d’une autre, le biais semble minime (i.e. &lt; 3% de différence dans nos estimés).</p>
<ol start="5" style="list-style-type: decimal">
<li>Vous vous rappelez subitement que dans les modèles de régression, lorsque vous utilisez un prédicteur continu comme <em>dcpct</em>, celui-ci doit être linéairement associé avec votre variable dépendante (i.e. la relation est une droite).<br />
5.1. En régression logistique, c’est avec le RC ou le log odds que les variables sont linéairement associées?<br />
<strong>Réponse:</strong>: Avec le log odds (i.e. <span class="math inline">\(log(P/(1-P))\)</span><br />
5.2. Vérifiez si la relation avec dcpct est linéaire. Quelles sont vos conclusions?</li>
</ol>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="régression-logistique.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous pourrions créer des variables au carré et au cube de dcpct après l&#39;avoir centré sur valeur moyenne (75%)</span></span>
<span id="cb230-2"><a href="régression-logistique.html#cb230-2" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dcpct_ct <span class="ot">&lt;-</span> nocardia<span class="sc">$</span>dcpct<span class="dv">-75</span></span>
<span id="cb230-3"><a href="régression-logistique.html#cb230-3" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dcpct_ct_sq <span class="ot">&lt;-</span> nocardia<span class="sc">$</span>dcpct_ct<span class="sc">*</span>nocardia<span class="sc">$</span>dcpct_ct</span>
<span id="cb230-4"><a href="régression-logistique.html#cb230-4" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dcpct_ct_cu <span class="ot">&lt;-</span> nocardia<span class="sc">$</span>dcpct_ct<span class="sc">*</span>nocardia<span class="sc">$</span>dcpct_ct<span class="sc">*</span>nocardia<span class="sc">$</span>dcpct_ct</span>
<span id="cb230-5"><a href="régression-logistique.html#cb230-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb230-6"><a href="régression-logistique.html#cb230-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Vérifions le modèle avec terme au carré (pour voir s&#39;il y a une courbe)</span></span>
<span id="cb230-7"><a href="régression-logistique.html#cb230-7" aria-hidden="true" tabindex="-1"></a>modele_carre <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb230-8"><a href="régression-logistique.html#cb230-8" aria-hidden="true" tabindex="-1"></a>                    casecont <span class="sc">~</span> dcpct_ct <span class="sc">+</span> dcpct_ct_sq, </span>
<span id="cb230-9"><a href="régression-logistique.html#cb230-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">family=</span><span class="st">&quot;binomial&quot;</span></span>
<span id="cb230-10"><a href="régression-logistique.html#cb230-10" aria-hidden="true" tabindex="-1"></a>                    )</span>
<span id="cb230-11"><a href="régression-logistique.html#cb230-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_carre)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = casecont ~ dcpct_ct + dcpct_ct_sq, family = &quot;binomial&quot;, 
##     data = nocardia)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3821  -1.3332   0.2478   1.0292   2.0633  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  0.4503912  0.4348605   1.036    0.300
## dcpct_ct     0.0056391  0.0119672   0.471    0.637
## dcpct_ct_sq -0.0003716  0.0002956  -1.257    0.209
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 149.72  on 107  degrees of freedom
## Residual deviance: 136.50  on 105  degrees of freedom
## AIC: 142.5
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><strong>Réponse:</strong> On peut vérifier si la relation est linéaire en ajoutant <span class="math inline">\(dcpct^2\)</span>, puis, si nécessaire, <span class="math inline">\(dcpct^2\)</span> et <span class="math inline">\(dcpct^3\)</span> au modèle. Bien sûr, ce n’est pas une mauvaise idée de centrer <em>dcpct</em> (sur sa moyenne par exemple) avant de faire ces transformations afin d’éviter toute colinéarité. Dans ce cas, le coefficient pour <span class="math inline">\(dcpct^2\)</span> n’est pas significatif (<em>P</em> = 0.21). Une courbe ne semble donc pas être nécessaire. C’est donc probablement inutile d’aller vérifier si de multiples points d’inflexions (i.e. <span class="math inline">\(dcpct^3\)</span>) sont nécessaires. Si vous l’avez tout de même fait, vous aurez noté des valeurs de P de 0.68 et de 0.40 pour les termes au carré et au cube, respectivement. Donc la relation entre <em>dcpct</em> et le log odds de nocardiose semble être linéaire et pourra être modélisée sans l’ajout de termes polynomiaux.</p>
<ol start="6" style="list-style-type: decimal">
<li>Maintenant modélisez l’interaction entre neomycine et cloxacilline dans votre modèle avec <em>dneo</em> <em>dclox</em> <em>dcpct</em> et <em>dbarn</em>.</li>
</ol>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="régression-logistique.html#cb232-1" aria-hidden="true" tabindex="-1"></a>modele_inter <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>nocardia, </span>
<span id="cb232-2"><a href="régression-logistique.html#cb232-2" aria-hidden="true" tabindex="-1"></a>                    casecont <span class="sc">~</span> dneo<span class="sc">*</span>dclox <span class="sc">+</span> dbarn <span class="sc">+</span> dcpct, </span>
<span id="cb232-3"><a href="régression-logistique.html#cb232-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">family=</span><span class="st">&quot;binomial&quot;</span></span>
<span id="cb232-4"><a href="régression-logistique.html#cb232-4" aria-hidden="true" tabindex="-1"></a>                    )</span></code></pre></div>
<p>6.1. Quelles seraient les odds de nocardiose (et IC 95%) dans les troupeaux où cloxacilline et néomycine sont utilisées <em>vs.</em> ceux où aucun de ces traitements ne sont utilisés? Ces troupeaux sont-ils significativement différents?</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="régression-logistique.html#cb233-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb233-2"><a href="régression-logistique.html#cb233-2" aria-hidden="true" tabindex="-1"></a>contrast <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(modele_inter, </span>
<span id="cb233-3"><a href="régression-logistique.html#cb233-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">c</span>(<span class="st">&quot;dneo&quot;</span>, </span>
<span id="cb233-4"><a href="régression-logistique.html#cb233-4" aria-hidden="true" tabindex="-1"></a>                      <span class="st">&quot;dclox&quot;</span>)</span>
<span id="cb233-5"><a href="régression-logistique.html#cb233-5" aria-hidden="true" tabindex="-1"></a>                    ) </span>
<span id="cb233-6"><a href="régression-logistique.html#cb233-6" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">pairs</span>(contrast, </span>
<span id="cb233-7"><a href="régression-logistique.html#cb233-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb233-8"><a href="régression-logistique.html#cb233-8" aria-hidden="true" tabindex="-1"></a>        ) </span></code></pre></div>
<pre><code>##  contrast                    odds.ratio      SE  df asymp.LCL asymp.UCL
##  dneo0 dclox0 / dneo1 dclox0     0.0215  0.0206 Inf   0.00182     0.254
##  dneo0 dclox0 / dneo0 dclox1     0.4266  0.4635 Inf   0.02617     6.954
##  dneo0 dclox0 / dneo1 dclox1     0.1573  0.1695 Inf   0.00988     2.504
##  dneo1 dclox0 / dneo0 dclox1    19.8672 16.5247 Inf   2.34494   168.323
##  dneo1 dclox0 / dneo1 dclox1     7.3257  5.0901 Inf   1.22922    43.659
##  dneo0 dclox1 / dneo1 dclox1     0.3687  0.3452 Inf   0.03329     4.084
## 
## Results are averaged over the levels of: dbarn 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 4 estimates 
## Intervals are back-transformed from the log odds ratio scale</code></pre>
<p><strong>Réponse:</strong> Ce serait la 3ième ligne de la table précédente. Donc RC (IC95): 0.16 (0.01, 2.5). Comme la valeur nulle (1.0) est incluse dans l’IC95, il n’y a pas de différence significative dans les odds de nocardia entre ces deux types de troupeau.</p>
<p>6.2. Quel serait les odds de nocardiose (et IC 95%) dans les troupeaux où cloxacilline et néomycine sont utilisés vs. ceux où seulement neomycine est utilisé? Ces troupeaux sont-ils significativement différents?<br />
<strong>Réponse:</strong> Ce serait la 5ième ligne de la table précédente. Donc RC (IC95): 7.3 (1.2, 43.7). Comme la valeur nulle (1.0) n’est pas incluse dans l’IC95, il y a une différence significative dans les odds de nocardia entre ces deux types de troupeau.</p>
</div>
</div>
<div id="travaux-pratiques-5---régression-logistique---évaluation-du-modèle" class="section level2 hasAnchor" number="7.15">
<h2><span class="header-section-number">7.15</span> Travaux pratiques 5 - Régression logistique - Évaluation du modèle<a href="régression-logistique.html#travaux-pratiques-5---régression-logistique---évaluation-du-modèle" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercices-4" class="section level3 hasAnchor" number="7.15.1">
<h3><span class="header-section-number">7.15.1</span> Exercices<a href="régression-logistique.html#exercices-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour ce TP utilisez le fichier Nocardia (voir description VER p.823).</p>
<p>Utilisez le modèle suivant: <span class="math inline">\(logit(Pcasecont=1) = β_0 + β_1*dneo + β_2*dclox + β_3*dneo*dclox + β_4*dcpct\)</span></p>
<ol style="list-style-type: decimal">
<li>Lorsqu’une interaction est présente, il devient difficile de présenter clairement vos résultats. À l’aide de la fonction <code>pairs()</code> du package <code>emmeans</code> vous seriez cependant capable de créer une table comme proposée dans Knol et VanderWeele (2012) <a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>. Une autre manière consisterait à présenter l’effet de vos prédicteurs graphiquement sur une échelle de probabilité. Présentez ce graphique. Quel groupe de troupeaux se démarque particulièrement des autres en terme de probabilité de nocardiose?</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li><p>Évaluez l’adéquation du modèle. Quels sont les résultats et votre interprétation du test de Hosmer-Lemeshow?</p></li>
<li><p>La valeur prédictive d’un modèle peut également être évaluée à l’aide d’une courbe ROC. Représenter graphiquement la courbe ROC. Quelle est l’aire sous la courbe pour votre modèle ? Quelles seraient la sensibilité et la spécificité de votre modèle si on fixe un seuil de 50% (i.e. si modèle prédit probabilité de nocardiose &gt; 50% alors on diagnostique le troupeau comme nocardia positif)?</p></li>
<li><p>Quel est le profil d’observation avec le résiduel de Pearson le plus élevé? Combien y-a-t-il d’observations dans ce profil?</p></li>
<li><p>Quel profil d’observation avait le plus d’influence sur le coefficient de régression de <em>dcpct</em>? Pourquoi à votre opinion?</p></li>
</ol>
</div>
<div id="code-r-et-réponses-4" class="section level3 hasAnchor" number="7.15.2">
<h3><span class="header-section-number">7.15.2</span> Code R et réponses<a href="régression-logistique.html#code-r-et-réponses-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour ce TP utilisez le fichier Nocardia (voir description VER p.823).</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="régression-logistique.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous importons ce jeu de données</span></span>
<span id="cb235-2"><a href="régression-logistique.html#cb235-2" aria-hidden="true" tabindex="-1"></a>nocardia <span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">&quot;nocardia.csv&quot;</span>, </span>
<span id="cb235-3"><a href="régression-logistique.html#cb235-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">header=</span><span class="cn">TRUE</span>, </span>
<span id="cb235-4"><a href="régression-logistique.html#cb235-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sep=</span><span class="st">&quot;;&quot;</span></span>
<span id="cb235-5"><a href="régression-logistique.html#cb235-5" aria-hidden="true" tabindex="-1"></a>                    )</span>
<span id="cb235-6"><a href="régression-logistique.html#cb235-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nocardia)</span></code></pre></div>
<pre><code>##   id casecont numcow prod        bscc dbarn dout dcprep dcpct dneo dclox doth
## 1  1        0     16 20,1 446,2000122     2    1      4     0    0     0    1
## 2  2        0     16 22,3         214     2    1      3   100    1     0    1
## 3  3        0     18 24,9         260     2    1      3    25    0     0    1
## 4  4        0     18      184,1999969     1    1      3     1    0     0    1
## 5  5        0     20 34,5 61,40000153     2    1      3   100    0     1    0
## 6  6        0     21 22,7 80,19999695     1    1      3     0    0     0    0</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="régression-logistique.html#cb237-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous indiquons les variables catégoriques dans le jeu de données</span></span>
<span id="cb237-2"><a href="régression-logistique.html#cb237-2" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dbarn <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dbarn) </span>
<span id="cb237-3"><a href="régression-logistique.html#cb237-3" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dneo <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dneo) </span>
<span id="cb237-4"><a href="régression-logistique.html#cb237-4" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>dclox <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>dclox) </span>
<span id="cb237-5"><a href="régression-logistique.html#cb237-5" aria-hidden="true" tabindex="-1"></a>nocardia<span class="sc">$</span>casecont <span class="ot">&lt;-</span> <span class="fu">factor</span>(nocardia<span class="sc">$</span>casecont) </span></code></pre></div>
<p>Utilisez le modèle suivant: <span class="math inline">\(logit(Pcasecont=1) = β_0 + β_1*dneo + β_2*dclox + β_3*dneo*dclox + β_4*dcpct\)</span></p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="régression-logistique.html#cb238-1" aria-hidden="true" tabindex="-1"></a>modele <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> nocardia, </span>
<span id="cb238-2"><a href="régression-logistique.html#cb238-2" aria-hidden="true" tabindex="-1"></a>              casecont <span class="sc">~</span> dneo<span class="sc">*</span>dclox <span class="sc">+</span> dcpct, </span>
<span id="cb238-3"><a href="régression-logistique.html#cb238-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">family =</span> binomial</span>
<span id="cb238-4"><a href="régression-logistique.html#cb238-4" aria-hidden="true" tabindex="-1"></a>              )</span></code></pre></div>
<ol style="list-style-type: decimal">
<li>Lorsqu’une interaction est présente, il devient difficile de présenter clairement vos résultats. À l’aide de la fonction <code>pairs()</code> du package <code>emmeans</code> vous seriez cependant capable de créer une table comme proposée dans Knol et VanderWeele (2012). Une autre manière consisterait à présenter l’effet de vos prédicteurs graphiquement sur une échelle de probabilité. Présentez ce graphique. Quel groupe de troupeaux se démarque particulièrement des autres en terme de probabilité de nocardiose?</li>
</ol>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="régression-logistique.html#cb239-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb239-2"><a href="régression-logistique.html#cb239-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(modele, </span>
<span id="cb239-3"><a href="régression-logistique.html#cb239-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">type=</span><span class="st">&quot;eff&quot;</span>, </span>
<span id="cb239-4"><a href="régression-logistique.html#cb239-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">terms=</span><span class="fu">c</span>(<span class="st">&quot;dcpct&quot;</span>, </span>
<span id="cb239-5"><a href="régression-logistique.html#cb239-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;dneo&quot;</span>, </span>
<span id="cb239-6"><a href="régression-logistique.html#cb239-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;dclox&quot;</span>)</span>
<span id="cb239-7"><a href="régression-logistique.html#cb239-7" aria-hidden="true" tabindex="-1"></a>           )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-257"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-257-1.png" alt="Effet sur la probabilité de nocardia de l'utilisation de la neomycine et du % de vache traitées au tarissement par niveau d'utilisation de la cloxacilline." width="672" />
<p class="caption">
Figure 7.8: Effet sur la probabilité de nocardia de l’utilisation de la neomycine et du % de vache traitées au tarissement par niveau d’utilisation de la cloxacilline.
</p>
</div>
<p><strong>Réponse:</strong> Les troupeaux utilisant seulement la néomycine (sans cloxacilline) semblent avoir une probabilité beaucoup
plus élevée de nocardiose.</p>
<ol start="2" style="list-style-type: decimal">
<li>Évaluez l’adéquation du modèle. Quels sont les résultats et votre interprétation du test de Hosmer-Lemeshow?</li>
</ol>
<p><strong>Réponse:</strong></p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="régression-logistique.html#cb240-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb240-2"><a href="régression-logistique.html#cb240-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(modele<span class="sc">$</span>y, </span>
<span id="cb240-3"><a href="régression-logistique.html#cb240-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">fitted</span>(modele), </span>
<span id="cb240-4"><a href="régression-logistique.html#cb240-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">g=</span><span class="dv">8</span></span>
<span id="cb240-5"><a href="régression-logistique.html#cb240-5" aria-hidden="true" tabindex="-1"></a>            )</span></code></pre></div>
<pre><code>## 
##  Hosmer and Lemeshow goodness of fit (GOF) test
## 
## data:  modele$y, fitted(modele)
## X-squared = 1.4887, df = 6, p-value = 0.9602</code></pre>
<p>Interprétation: Le modèle est adéquat (<em>P</em>=0.96).</p>
<ol start="3" style="list-style-type: decimal">
<li>La valeur prédictive d’un modèle peut également être évaluée à l’aide d’une courbe ROC. Représenter graphiquement la courbe ROC. Quelle est l’aire sous la courbe pour votre modèle ? Quelles seraient la sensibilité et la spécificité de votre modèle si on fixe un seuil de 50% (i.e. si modèle prédit probabilité de nocardiose &gt; 50% alors on diagnostique le troupeau comme nocardia positif)?</li>
</ol>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="régression-logistique.html#cb242-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb242-2"><a href="régression-logistique.html#cb242-2" aria-hidden="true" tabindex="-1"></a>diag <span class="ot">&lt;-</span> <span class="fu">augment</span>(modele) <span class="co">#Nous venons de créer une nouvelle table dans laquelle les résiduels, distance de cook, etc se trouvent maintenant</span></span>
<span id="cb242-3"><a href="régression-logistique.html#cb242-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb242-4"><a href="régression-logistique.html#cb242-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous ajoutons les valeurs prédites de l&#39;objet modele</span></span>
<span id="cb242-5"><a href="régression-logistique.html#cb242-5" aria-hidden="true" tabindex="-1"></a>diag<span class="sc">$</span>pred_prob <span class="ot">&lt;-</span> modele<span class="sc">$</span>fitted.values</span>
<span id="cb242-6"><a href="régression-logistique.html#cb242-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb242-7"><a href="régression-logistique.html#cb242-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous génèrons l&#39;objet ROC.</span></span>
<span id="cb242-8"><a href="régression-logistique.html#cb242-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb242-9"><a href="régression-logistique.html#cb242-9" aria-hidden="true" tabindex="-1"></a>roc_data <span class="ot">&lt;-</span> <span class="fu">roc</span>(<span class="at">data=</span>diag, </span>
<span id="cb242-10"><a href="régression-logistique.html#cb242-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">response=</span><span class="st">&quot;casecont&quot;</span>, </span>
<span id="cb242-11"><a href="régression-logistique.html#cb242-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">predictor=</span><span class="st">&quot;pred_prob&quot;</span></span>
<span id="cb242-12"><a href="régression-logistique.html#cb242-12" aria-hidden="true" tabindex="-1"></a>                )</span>
<span id="cb242-13"><a href="régression-logistique.html#cb242-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb242-14"><a href="régression-logistique.html#cb242-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Puis la courbe ROC</span></span>
<span id="cb242-15"><a href="régression-logistique.html#cb242-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.roc</span>(roc_data, </span>
<span id="cb242-16"><a href="régression-logistique.html#cb242-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">print.auc =</span> <span class="cn">TRUE</span>, </span>
<span id="cb242-17"><a href="régression-logistique.html#cb242-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">grid =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-259"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-259-1.png" alt="Courbe ROC." width="672" />
<p class="caption">
Figure 7.9: Courbe ROC.
</p>
</div>
<p><strong>Réponse:</strong> L’aire sous la courbe est 0.850. Avec une table, ce sera facile de trouver les Se et Sp pour différents seuils.</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="régression-logistique.html#cb243-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Présenter les sensibilités et spécificités des différents seuils dans une même table.</span></span>
<span id="cb243-2"><a href="régression-logistique.html#cb243-2" aria-hidden="true" tabindex="-1"></a>accu <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">Seuil=</span>roc_data<span class="sc">$</span>thresholds, </span>
<span id="cb243-3"><a href="régression-logistique.html#cb243-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Se=</span>roc_data<span class="sc">$</span>sensitivities, </span>
<span id="cb243-4"><a href="régression-logistique.html#cb243-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Sp=</span>roc_data<span class="sc">$</span>specificities), </span>
<span id="cb243-5"><a href="régression-logistique.html#cb243-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">digits=</span><span class="dv">2</span>))</span>
<span id="cb243-6"><a href="régression-logistique.html#cb243-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb243-7"><a href="régression-logistique.html#cb243-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Voir la table</span></span>
<span id="cb243-8"><a href="régression-logistique.html#cb243-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb243-9"><a href="régression-logistique.html#cb243-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb243-10"><a href="régression-logistique.html#cb243-10" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(accu,  </span>
<span id="cb243-11"><a href="régression-logistique.html#cb243-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Sensibilité et spécificité du modèle pour différents seuils de probabilité prédite.&quot;</span>)<span class="sc">%&gt;%</span></span>
<span id="cb243-12"><a href="régression-logistique.html#cb243-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-260">Table 7.4: </span>Sensibilité et spécificité du modèle pour différents seuils de probabilité prédite.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Seuil
</th>
<th style="text-align:right;">
Se
</th>
<th style="text-align:right;">
Sp
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
-Inf
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.13
</td>
</tr>
<tr>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.15
</td>
</tr>
<tr>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.17
</td>
</tr>
<tr>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.17
</td>
</tr>
<tr>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.19
</td>
</tr>
<tr>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.20
</td>
</tr>
<tr>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.22
</td>
</tr>
<tr>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
0.24
</td>
</tr>
<tr>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
0.96
</td>
<td style="text-align:right;">
0.26
</td>
</tr>
<tr>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:right;">
0.96
</td>
<td style="text-align:right;">
0.28
</td>
</tr>
<tr>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:right;">
0.94
</td>
<td style="text-align:right;">
0.41
</td>
</tr>
<tr>
<td style="text-align:right;">
0.22
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
0.41
</td>
</tr>
<tr>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:right;">
0.57
</td>
</tr>
<tr>
<td style="text-align:right;">
0.32
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:right;">
0.59
</td>
</tr>
<tr>
<td style="text-align:right;">
0.35
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:right;">
0.61
</td>
</tr>
<tr>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.61
</td>
</tr>
<tr>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.63
</td>
</tr>
<tr>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.69
</td>
</tr>
<tr>
<td style="text-align:right;">
0.39
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.70
</td>
</tr>
<tr>
<td style="text-align:right;">
0.41
</td>
<td style="text-align:right;">
0.80
</td>
<td style="text-align:right;">
0.80
</td>
</tr>
<tr>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.80
</td>
<td style="text-align:right;">
0.81
</td>
</tr>
<tr>
<td style="text-align:right;">
0.48
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
0.83
</td>
</tr>
<tr>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
0.83
</td>
</tr>
<tr>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
0.85
</td>
</tr>
<tr>
<td style="text-align:right;">
0.60
</td>
<td style="text-align:right;">
0.74
</td>
<td style="text-align:right;">
0.85
</td>
</tr>
<tr>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
0.87
</td>
</tr>
<tr>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
0.91
</td>
</tr>
<tr>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:right;">
0.63
</td>
<td style="text-align:right;">
0.91
</td>
</tr>
<tr>
<td style="text-align:right;">
0.84
</td>
<td style="text-align:right;">
0.61
</td>
<td style="text-align:right;">
0.91
</td>
</tr>
<tr>
<td style="text-align:right;">
Inf
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1.00
</td>
</tr>
</tbody>
</table>
<p><strong>Réponse:</strong> On note des Se et Sp de 0.76 et 0.83, respectivement lorsqu’on fixe le seuil de probabilité à &gt;0.50 (en fait 0.51 et plus).</p>
<ol start="4" style="list-style-type: decimal">
<li>Quel est le profil d’observations avec le résiduel de Pearson le plus élevé? Combien y-a-t-il d’observations dans ce profil?</li>
</ol>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="régression-logistique.html#cb244-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous pourrions maintenant ordonner cette table pour voir les 10 observations avec les résiduels les plus larges</span></span>
<span id="cb244-2"><a href="régression-logistique.html#cb244-2" aria-hidden="true" tabindex="-1"></a>diag_maxres <span class="ot">&lt;-</span> diag[<span class="fu">order</span>(<span class="sc">-</span>diag<span class="sc">$</span>.resid),]</span>
<span id="cb244-3"><a href="régression-logistique.html#cb244-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diag_maxres, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 11
##    casecont dneo  dclox dcpct .fitted .resid .std.resid   .hat .sigma .cooksd
##    &lt;fct&gt;    &lt;fct&gt; &lt;fct&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
##  1 1        0     0        10  -3.55    2.68       2.71 0.0243  0.971  0.178 
##  2 1        1     1        50  -1.57    1.87       1.93 0.0592  0.989  0.0641
##  3 1        0     0       100  -1.52    1.85       1.94 0.0901  0.988  0.0990
##  4 1        0     1        83  -1.45    1.82       1.89 0.0707  0.989  0.0700
##  5 1        0     1       100  -1.07    1.65       1.73 0.0847  0.992  0.0589
##  6 1        0     1       100  -1.07    1.65       1.73 0.0847  0.992  0.0589
##  7 1        1     0         1  -0.570   1.43       1.50 0.0893  0.996  0.0381
##  8 1        1     1       100  -0.437   1.37       1.42 0.0757  0.997  0.0275
##  9 1        1     1       100  -0.437   1.37       1.42 0.0757  0.997  0.0275
## 10 1        1     1       100  -0.437   1.37       1.42 0.0757  0.997  0.0275
## # … with 1 more variable: pred_prob &lt;dbl&gt;</code></pre>
<p><strong>Réponse:</strong> Le modèle prédit une probabilité de moins de 3% de nocardiose dans un troupeau qui n’utilise ni neomycine, ni cloxacilline et où 10% des vaches sont traitées au tarissement. Il y a une seule observation dans ce profil et il s’agit d’un troupeau positif à nocardia (d’où le résiduel très large).</p>
<ol start="5" style="list-style-type: decimal">
<li>Quel profil d’observations avait le plus d’influence sur le coefficient de régression de <em>dcpct</em>? Pourquoi à votre opinion?</li>
</ol>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="régression-logistique.html#cb246-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous pourrions maintenant ordonner cette table pour voir les 10 observations avec les leviers les plus larges</span></span>
<span id="cb246-2"><a href="régression-logistique.html#cb246-2" aria-hidden="true" tabindex="-1"></a>diag_cook <span class="ot">&lt;-</span> diag[<span class="fu">order</span>(<span class="sc">-</span>diag<span class="sc">$</span>.cooksd),]</span>
<span id="cb246-3"><a href="régression-logistique.html#cb246-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diag_cook, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 11
##    casecont dneo  dclox dcpct .fitted .resid .std.resid   .hat .sigma .cooksd
##    &lt;fct&gt;    &lt;fct&gt; &lt;fct&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
##  1 1        0     0        10  -3.55    2.68       2.71 0.0243  0.971  0.178 
##  2 1        0     0       100  -1.52    1.85       1.94 0.0901  0.988  0.0990
##  3 1        0     1        83  -1.45    1.82       1.89 0.0707  0.989  0.0700
##  4 1        1     1        50  -1.57    1.87       1.93 0.0592  0.989  0.0641
##  5 1        0     1       100  -1.07    1.65       1.73 0.0847  0.992  0.0589
##  6 1        0     1       100  -1.07    1.65       1.73 0.0847  0.992  0.0589
##  7 1        1     0         1  -0.570   1.43       1.50 0.0893  0.996  0.0381
##  8 1        1     1       100  -0.437   1.37       1.42 0.0757  0.997  0.0275
##  9 1        1     1       100  -0.437   1.37       1.42 0.0757  0.997  0.0275
## 10 1        1     1       100  -0.437   1.37       1.42 0.0757  0.997  0.0275
## # … with 1 more variable: pred_prob &lt;dbl&gt;</code></pre>
<p><strong>Réponse:</strong> C’est le même profil identifié à la question 5. En général, une augmentation de dcpct entraine une augmentation de la probabilité de nocardia, mais cette observation à un dcpct bas (10% ; le 15ième plus bas du jeu de donnée), mais le troupeau était tout de même un troupeau cas. Ce profil tire donc la droite de régression vers lui (et modifie donc le coefficient de régression).</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p><a href="https://pubmed.ncbi.nlm.nih.gov/22253321/">Recommendations for presenting analyses of effect modification and interaction. M. J. Knol and T. J. VanderWeele, Int J Epidemiol 2012 Vol. 41 Issue 2 Pages 514-20</a><a href="régression-logistique.html#fnref5" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="régression-linéaire.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="régression-pour-données-de-compte-et-dincidence.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labo R Bookdown project.pdf", "Labo R Bookdown project.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
