<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre 7 Travaux pratiques 1 - Régression linéaire - Base | Épidémiologie 2 - Labo informatique R (PTM-6675)</title>
  <meta name="description" content="Les notes de cours pour la partie TP du cours d'Épi2" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre 7 Travaux pratiques 1 - Régression linéaire - Base | Épidémiologie 2 - Labo informatique R (PTM-6675)" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Les notes de cours pour la partie TP du cours d'Épi2" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre 7 Travaux pratiques 1 - Régression linéaire - Base | Épidémiologie 2 - Labo informatique R (PTM-6675)" />
  
  <meta name="twitter:description" content="Les notes de cours pour la partie TP du cours d'Épi2" />
  

<meta name="author" content="Simon Dufour (Professeur à la Faculté de Médecine vétérinaire de l'Université de Montréal)" />


<meta name="date" content="2021-02-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="régression-linéaire.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Épidémiologie 2 - Labo informatique R (PTM-6675)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> À propos</a></li>
<li class="chapter" data-level="2" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html"><i class="fa fa-check"></i><b>2</b> Bonnes pratiques de gestion de projet</a><ul>
<li class="chapter" data-level="2.1" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#organiser-son-projet-de-recherche"><i class="fa fa-check"></i><b>2.1</b> Organiser son projet de recherche</a></li>
<li class="chapter" data-level="2.2" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#où-sauvegarder-son-projet"><i class="fa fa-check"></i><b>2.2</b> Où sauvegarder son projet</a></li>
<li class="chapter" data-level="2.3" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#où-sauvegarder-ses-données"><i class="fa fa-check"></i><b>2.3</b> Où sauvegarder ses données</a></li>
<li class="chapter" data-level="2.4" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#scripts-danalyse"><i class="fa fa-check"></i><b>2.4</b> Scripts d'analyse</a></li>
<li class="chapter" data-level="2.5" data-path="bonnes-pratiques-de-gestion-de-projet.html"><a href="bonnes-pratiques-de-gestion-de-projet.html#copies-de-sécurité"><i class="fa fa-check"></i><b>2.5</b> Copies de sécurité</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="obtention-des-données-pour-les-travaux-pratiques.html"><a href="obtention-des-données-pour-les-travaux-pratiques.html"><i class="fa fa-check"></i><b>3</b> Obtention des données pour les travaux pratiques</a></li>
<li class="chapter" data-level="4" data-path="aide-de-r.html"><a href="aide-de-r.html"><i class="fa fa-check"></i><b>4</b> Aide de R</a></li>
<li class="chapter" data-level="5" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>5</b> R Markdown</a></li>
<li class="chapter" data-level="6" data-path="régression-linéaire.html"><a href="régression-linéaire.html"><i class="fa fa-check"></i><b>6</b> Régression linéaire</a><ul>
<li class="chapter" data-level="6.1" data-path="régression-linéaire.html"><a href="régression-linéaire.html#généralités"><i class="fa fa-check"></i><b>6.1</b> Généralités</a></li>
<li class="chapter" data-level="6.2" data-path="régression-linéaire.html"><a href="régression-linéaire.html#ajouter-des-intervalles-de-confiance"><i class="fa fa-check"></i><b>6.2</b> Ajouter des intervalles de confiance</a></li>
<li class="chapter" data-level="6.3" data-path="régression-linéaire.html"><a href="régression-linéaire.html#test-de-f-pour-comparer-modèles-complet-vs.-réduit"><i class="fa fa-check"></i><b>6.3</b> Test de <em>F</em> pour comparer modèles complet <em>vs.</em> réduit</a></li>
<li class="chapter" data-level="6.4" data-path="régression-linéaire.html"><a href="régression-linéaire.html#transformer-une-variable"><i class="fa fa-check"></i><b>6.4</b> Transformer une variable</a></li>
<li class="chapter" data-level="6.5" data-path="régression-linéaire.html"><a href="régression-linéaire.html#choisir-la-valeur-de-référence-pour-une-variable-catégorique"><i class="fa fa-check"></i><b>6.5</b> Choisir la valeur de référence pour une variable catégorique</a></li>
<li class="chapter" data-level="6.6" data-path="régression-linéaire.html"><a href="régression-linéaire.html#comparer-les-niveaux-dun-prédicteur-catégorique-avec-2-catégories"><i class="fa fa-check"></i><b>6.6</b> Comparer les niveaux d’un prédicteur catégorique avec &gt;2 catégories</a></li>
<li class="chapter" data-level="6.7" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluer-une-interaction-entre-2-variables"><i class="fa fa-check"></i><b>6.7</b> Évaluer une interaction entre 2 variables</a></li>
<li class="chapter" data-level="6.8" data-path="régression-linéaire.html"><a href="régression-linéaire.html#tol-et-vif---évaluer-colinéarité"><i class="fa fa-check"></i><b>6.8</b> TOL et VIF - Évaluer colinéarité</a></li>
<li class="chapter" data-level="6.9" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluation-du-modèle"><i class="fa fa-check"></i><b>6.9</b> Évaluation du modèle</a><ul>
<li class="chapter" data-level="6.9.1" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluer-la-linéarité-de-la-relation-à-laide-de-courbes-lissées-pour-prédicteur-quantitatif"><i class="fa fa-check"></i><b>6.9.1</b> Évaluer la linéarité de la relation à l'aide de courbes lissées (pour prédicteur quantitatif)</a></li>
<li class="chapter" data-level="6.9.2" data-path="régression-linéaire.html"><a href="régression-linéaire.html#méthodes-diagnostiques-pour-les-résiduels"><i class="fa fa-check"></i><b>6.9.2</b> Méthodes diagnostiques pour les résiduels</a></li>
<li class="chapter" data-level="6.9.3" data-path="régression-linéaire.html"><a href="régression-linéaire.html#évaluation-des-observations-extrêmes-etou-influentes"><i class="fa fa-check"></i><b>6.9.3</b> Évaluation des observations extrêmes et/ou influentes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="travaux-pratiques-1-régression-linéaire-base.html"><a href="travaux-pratiques-1-régression-linéaire-base.html"><i class="fa fa-check"></i><b>7</b> Travaux pratiques 1 - Régression linéaire - Base</a><ul>
<li class="chapter" data-level="7.1" data-path="travaux-pratiques-1-régression-linéaire-base.html"><a href="travaux-pratiques-1-régression-linéaire-base.html#exercices"><i class="fa fa-check"></i><b>7.1</b> Exercices</a></li>
<li class="chapter" data-level="7.2" data-path="travaux-pratiques-1-régression-linéaire-base.html"><a href="travaux-pratiques-1-régression-linéaire-base.html#code-r-et-réponses"><i class="fa fa-check"></i><b>7.2</b> Code R et réponses</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publié avec bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Épidémiologie 2 - Labo informatique R (PTM-6675)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="travaux-pratiques-1---régression-linéaire---base" class="section level1">
<h1><span class="header-section-number">Chapitre 7</span> Travaux pratiques 1 - Régression linéaire - Base</h1>
<div id="exercices" class="section level2">
<h2><span class="header-section-number">7.1</span> Exercices</h2>
<p>Pour ce TP utilisez le fichier DAISY2 (voir description VER p.809).</p>
<p><strong>Ne sélectionnez que les 7 troupeaux avec h7=1. </strong></p>
<p><strong>1)</strong> Considérons le <strong>nombre de jours jusqu’à la saillie fécondante (WPC) comme variable dépendante</strong> et vérifions comment différents prédicteurs permettent de prédire cet intervalle.</p>
<p><strong>a.</strong> Représenter graphiquement l’association entre milk120 et WPC. Pensez-vous qu’une ligne droite passant au travers des points capture adéquatement la relation entre ces deux variables ?</p>
<p><strong>b.</strong> Faites varier le lissage (e.g. 0.1 ou 1) et décrivez comment la courbe lissée change en fonction de ce lissage.</p>
<p><strong>c.</strong> Maintenant, représenter graphiquement la relation entre parity et wpc. Dans ce cas, pensez-vous qu’une ligne droite passant au travers des points capture adéquatement la relation entre ces deux variables ?</p>
<p><strong>d.</strong> À partir du diagramme de dispersion, il est raisonnable de penser que l’intervalle WPC change linéairement avec parity. Cette relation linéaire peut être exprimée par le modèle <span class="math inline">\(WPC= β_0 + β_1*parity\)</span>. À l’aide d’un modèle de régression linéaire, estimer les valeurs de <span class="math inline">\(β_0\)</span> et <span class="math inline">\(β_1\)</span>. Écrivez l’équation de régression sous la forme donnée ci-dessus, avec ces estimés dans l’équation. Comment interprétez-vous ces estimés ?</p>
<p><strong>e.</strong> Un test de <em>F</em> vous est rapporté pour le modèle de même qu’un test de <em>T</em> pour le coefficient de régression de parity (i.e. <span class="math inline">\(β_1\)</span>). Quelles sont les hypothèses nulles pour chacun de ces tests? Dans ce cas, ces 2 tests sont-ils réellement différents?</p>
<p><strong>f.</strong> Quel serait l’IC95% pour le coefficient de régression de parity?</p>
<p><strong>g.</strong> Existe-t’il une relation linéaire statistiquement significative entre ces 2 variables?</p>
<p><strong>h.</strong> Le nombre de jours jusqu’à la saillie fécondante (WPC) pour une parité zéro n’a bien sûr pas de sens biologique. Pour repositionner ce paramètre à la parité minimale observée (i.e. parity=1), on peut remplacer la parité par une nouvelle variable (parity_ct) centrée sur parity=1. Créez cette nouvelle variable et, à l’aide d’un modèle de régression linéaire, estimez les valeurs de <span class="math inline">\(β_0\)</span> et <span class="math inline">\(β_1\)</span> et interprétez les coefficients de régression comme à la question 1.d.</p>
<p><strong>2)</strong> À la question 1.a, nous avons vu que la relation entre milk120 et WPC ne semble pas être linéaire. Nous pourrions donc créer des termes polynomiaux afin de modéliser correctement cette association.</p>
<p><strong>a.</strong> Créer une nouvelle variable milk120_ct centrée sur la production moyenne. Puis créez 1 terme polynomial milk120_ct_sq (i.e. milk120 au carré). Vérifiez si l’ajout d’une courbe (i.e. le terme au carré) ajoute significativement au modèle.</p>
<p><strong>b.</strong> Selon votre analyse graphique réalisée à la question 1.a, pensez-vous que vous auriez besoin d’ajouter d’autres points d’inflexions pour bien représenter cette association? Vérifiez votre réponse en ajoutant un terme au cube pour milk120 en plus du terme au carré.</p>
<p><strong>c.</strong> Dans ce dernier modèle, vérifiez qu’il n’y a pas de problème sévère de colinéarité.</p>
<p><strong>3)</strong> Dans le modèle suivant <span class="math inline">\(wpc = β_0 +β_1parityct + β_2twin + β_3dyst\)</span> vous vous demandez si les problèmes de vêlage (i.e. twin et dyst ensemble) apporte significativement au modèle. Quel test pourriez-vous réaliser afin de répondre à cette question? Quel est le résultat de ce test et votre interprétation de ce résultat?</p>
<p><strong>4)</strong> Recodez maintenant parity afin d’avoir une nouvelle variable catégorique (parity_cat) à 3 niveaux (parity 1, parity 2 et parity ≥3). Vérifiez la relation entre parity_cat et WPC en vous assurant d’avoir parity 1 comme valeur de référence.</p>
<p><strong>a.</strong> Est-ce que parity_cat (comme variable) est significativement associée à WPC?</p>
<p><strong>b.</strong> De combien WPC change pour une vache de 2ième parité comparativement à une vache de 1ère parité?</p>
<p><strong>c.</strong> Quel est le WPC pour une vache de 1ère parité?</p>
<p><strong>d.</strong> Quelle est la différence de WPC entre une 2ième et une 3ième parité et quel est l’IC 95% ajusté pour comparaisons multiples pour cette différence? Cette différence est-elle statistiquement significative?</p>
<p><strong>5)</strong> Vous supposez que l’effet d’une dystocie (dyst) sur WPC varie en fonction de la parité (catégorique 1ère, 2ième, ou ≥3ième). Par exemple, une vache plus vieille ayant une dystocie aura possiblement un délai plus long jusqu’à la saille fécondante comparativement à une vache plus jeune.</p>
<p><strong>a.</strong> Que devrez-vous tester pour vérifier cette hypothèse?</p>
<p><strong>b.</strong> Effectuer ce test. Est-ce que l’effet de dystocie varie de manière statistiquement significative en fonction de la parité?</p>
<p><strong>c.</strong> Quel est le nombre de jours moyen jusqu’à la saillie fécondante pour chacune des catégories de parité et de dystocie (i.e. remplir le tableau suivant)? Pour quel niveau de parité les différences semblent les plus importantes?</p>
<table>
<caption><span id="tab:unnamed-chunk-34">Table 7.1: </span>Nombre moyen estimé de jours jusqu’à la saillie fécondante pour chacune des catégories de parité et de dystocie</caption>
<thead>
<tr class="header">
<th align="left">Parite</th>
<th align="left">Dystocie_0</th>
<th align="left">Dystocie_1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1ère lactation</td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">2ième lactation</td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">3ième ou plus</td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
</div>
<div id="code-r-et-réponses" class="section level2">
<h2><span class="header-section-number">7.2</span> Code R et réponses</h2>
<p>Pour ce TP utilisez le fichier DAISY2 (voir description VER p.809).<br />
<strong>Ne sélectionnez que les 7 troupeaux avec h7=1. </strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">daisy2_mod&lt;-<span class="kw">subset</span>(daisy2, h7<span class="op">==</span><span class="dv">1</span>)</code></pre></div>
<p><strong>1)</strong> Considérons le <strong>nombre de jours jusqu’à la saillie fécondante (WPC) comme variable dépendante</strong> et vérifions comment différents prédicteurs permettent de prédire cet intervalle.</p>
<p><strong>a.</strong> Représenter graphiquement l’association entre milk120 et WPC. Pensez-vous qu’une ligne droite passant au travers des points capture adéquatement la relation entre ces deux variables ?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(daisy2_mod, <span class="kw">aes</span>(milk120, wpc)) <span class="op">+</span><span class="st"> </span><span class="co">#Ici j&#39;ai simplement indiqué le jeu de données, puis les variables d&#39;intérêt</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">  </span><span class="co">#Je demande d&#39;ajouter le nuage de points (un &#39;scatterplot&#39;)</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;loess&quot;</span>, <span class="dt">span=</span><span class="dv">2</span>)<span class="op">+</span><span class="st"> </span><span class="co">#Je demande d&#39;ajouter la courbe lissée de type loess. L&#39;argument span me permet d&#39;ajuster le lissage </span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="co">#J&#39;aime bien avoir un fond blanc pour mes figures (un thème noir et blanc; theme_bw). C&#39;est futile, mais bon...</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-36"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-36-1.png" alt="Relation entre la production de lait en 120j (milk120) et le nombre de jours jusqu’à la saillie fécondante (wpc) avec courbe lissée avec un facteur de 2." width="672" />
<p class="caption">
Figure 7.1: Relation entre la production de lait en 120j (milk120) et le nombre de jours jusqu’à la saillie fécondante (wpc) avec courbe lissée avec un facteur de 2.
</p>
</div>
<p><strong>Réponse:</strong> Non, relation semble légèrement curvilinéaire</p>
<p><strong>b.</strong> Faites varier le lissage (e.g. 0.1 ou 1) et décrivez comment la courbe lissée change en fonction de ce lissage.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(daisy2_mod, <span class="kw">aes</span>(milk120, wpc)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;loess&quot;</span>, <span class="dt">span=</span><span class="fl">0.2</span>)<span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme_bw</span>() </code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-37"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-37-1.png" alt="Relation entre la production de lait en 120j (milk120) et le nombre de jours jusqu’à la saillie fécondante (wpc) avec courbe lissée avec un facteur de 0.2." width="672" />
<p class="caption">
Figure 7.2: Relation entre la production de lait en 120j (milk120) et le nombre de jours jusqu’à la saillie fécondante (wpc) avec courbe lissée avec un facteur de 0.2.
</p>
</div>
<p><strong>Réponse:</strong> Lorsqu’on réduit le <code>span</code>, la courbe permet de visualiser toutes les petites variations. Elle devient plus droite (i.e. plus insensible aux variations) lorsque le <code>span</code> augmente.</p>
<p><strong>c.</strong> Maintenant, représenter graphiquement la relation entre parity et wpc. Dans ce cas, pensez-vous qu’une ligne droite passant au travers des points capture adéquatement la relation entre ces deux variables ?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(daisy2_mod, <span class="kw">aes</span>(parity, wpc)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;loess&quot;</span>, <span class="dt">span=</span><span class="dv">2</span>)<span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme_bw</span>() </code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-38"></span>
<img src="Labo-R-Bookdown-project_files/figure-html/unnamed-chunk-38-1.png" alt="Relation entre parité (parity) et le nombre de jours jusqu’à la saillie fécondante (wpc) avec courbe lissée avec un facteur de 2." width="672" />
<p class="caption">
Figure 7.3: Relation entre parité (parity) et le nombre de jours jusqu’à la saillie fécondante (wpc) avec courbe lissée avec un facteur de 2.
</p>
</div>
<p><strong>Réponse:</strong> c. Oui, semble mieux</p>
<p><strong>d.</strong> À partir du diagramme de dispersion, il est raisonnable de penser que l’intervalle WPC change linéairement avec parity. Cette relation linéaire peut être exprimée par le modèle <span class="math inline">\(WPC= β_0 + β_1*parity\)</span>. À l’aide d’un modèle de régression linéaire, estimer les valeurs de <span class="math inline">\(β_0\)</span> et <span class="math inline">\(β_1\)</span>. Écrivez l’équation de régression sous la forme donnée ci-dessus, avec ces estimés dans l’équation. Comment interprétez-vous ces estimés ?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modele1&lt;-<span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(parity)) <span class="co">#J&#39;ai créé un nouvel objet qui s&#39;appelle modele1 et qui est une régression des variables parity sur wpc</span>
modele1 <span class="co">#Je demande à voir l&#39;objet modele</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wpc ~ (parity), data = daisy2_mod)
## 
## Coefficients:
## (Intercept)       parity  
##      65.218        1.312</code></pre>
<p><strong>Réponse:</strong> <span class="math inline">\(WPC= 65.2 + 1.3*parity\)</span><br />
Intervalle WPC moyen quand parité=0 est de 65.2j. On ajoute ensuite 1.3 jours à chaque fois qu’on ajoute une parité.</p>
<p><strong>e.</strong> Un test de <em>F</em> vous est rapporté pour le modèle de même qu’un test de <em>T</em> pour le coefficient de régression de parity (i.e. <span class="math inline">\(β_1\)</span>). Quelles sont les hypothèses nulles pour chacun de ces tests? Dans ce cas, ces 2 tests sont-ils réellement différents?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(modele1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wpc ~ (parity), data = daisy2_mod)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -67.47 -38.47 -15.15  24.16 227.53 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  65.2181     2.7090  24.075   &lt;2e-16 ***
## parity        1.3118     0.8706   1.507    0.132    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 51.58 on 1572 degrees of freedom
##   (402 observations deleted due to missingness)
## Multiple R-squared:  0.001442,   Adjusted R-squared:  0.000807 
## F-statistic: 2.271 on 1 and 1572 DF,  p-value: 0.1321</code></pre>
<p><strong>Réponse:</strong> Test de <em>F</em> (<em>P</em>=0.132): tous les coefficients (outre <span class="math inline">\(β_0\)</span>, l’intercept) = 0<br />
Test de <em>T</em> (aussi <em>P</em>=0.132): le coefficient de parity (<span class="math inline">\(β_1\)</span>) = 0<br />
Non, puisqu’il y a un seul coefficient de régression dans l’équation les 2 tests sont équivalents.</p>
<p><strong>f.</strong> Quel serait l’IC95% pour le coefficient de régression de parity?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(modele1)</code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) 59.9045164 70.531662
## parity      -0.3958026  3.019367</code></pre>
<p><strong>Réponse:</strong> -0.4 à 3.0 jours</p>
<p><strong>g.</strong> Existe-t’il une relation linéaire statistiquement significative entre ces 2 variables?<br />
<strong>Réponse:</strong> Non (<em>P</em>=0.13 et <em>IC95%</em> inclus 0)</p>
<p><strong>h.</strong> Le nombre de jours jusqu’à la saillie fécondante (WPC) pour une parité zéro n’a bien sûr pas de sens biologique. Pour repositionner ce paramètre à la parité minimale observée (i.e. parity=1), on peut remplacer la parité par une nouvelle variable (parity_ct) centrée sur parity=1. Créez cette nouvelle variable et, à l’aide d’un modèle de régression linéaire, estimez les valeurs de <span class="math inline">\(β_0\)</span> et <span class="math inline">\(β_1\)</span> et interprétez les coefficients de régression comme à la question 1.d.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">daisy2_mod<span class="op">$</span>par_ct &lt;-<span class="st"> </span>daisy2_mod<span class="op">$</span>parity<span class="op">-</span><span class="dv">1</span>
modele2&lt;-<span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(par_ct)) 
modele2</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wpc ~ (par_ct), data = daisy2_mod)
## 
## Coefficients:
## (Intercept)       par_ct  
##      66.530        1.312</code></pre>
<p><strong>Réponse:</strong> Intervalle <em>wpc</em> moyen quand parité=1 est de 66.5j. On ajoute ensuite 1.3 jours à chaque fois qu’on ajoute une parité.</p>
<p><strong>2)</strong> À la question 1.a, nous avons vu que la relation entre milk120 et WPC ne semble pas être linéaire. Nous pourrions donc créer des termes polynomiaux afin de modéliser correctement cette association.</p>
<p><strong>a.</strong> Créer une nouvelle variable milk120_ct centrée sur la production moyenne. Puis créez 1 terme polynomial milk120_ct_sq (i.e. milk120 au carré). Vérifiez si l’ajout d’une courbe (i.e. le terme au carré) ajoute significativement au modèle.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Vérifions d&#39;abord quelle est la moyenne de milk120</span>
<span class="kw">mean</span>(daisy2_mod<span class="op">$</span>milk120, <span class="dt">na.rm=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 3225.311</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Je créé la variable centrée sur 3225 et celle au carré</span>
daisy2_mod<span class="op">$</span>milk120_ct &lt;-<span class="st"> </span>daisy2_mod<span class="op">$</span>milk120<span class="op">-</span><span class="dv">3225</span>
daisy2_mod<span class="op">$</span>milk120_ct_sq &lt;-daisy2_mod<span class="op">$</span>milk120_ct<span class="op">*</span>daisy2_mod<span class="op">$</span>milk120_ct
<span class="co">#Vérifions que ça a bien focntionné</span>
<span class="kw">head</span>(daisy2_mod)</code></pre></div>
<pre><code>##   region herd cow study_lact herd_size mwp parity milk120    calv_dt cf fs cc
## 1      1    1   1          1       294  26      5  3505.8 1996-11-11 80 NA NA
## 2      1    1   2          1       294  26      5  3691.3 1997-01-12 64 NA NA
## 3      1    1   3          1       294  26      5  4173.0 1997-01-17 71  0 93
## 4      1    1   4          1       294  26      5  3727.3 1997-02-11 35  1 35
## 5      1    1   5          1       294  26      5  3090.8 1997-06-26 47  0 87
## 6      1    1   6          1       294  26      4  5041.2 1996-10-16 NA NA NA
##   wpc spc twin dyst rp vag_disch h7 par_ct milk120_ct milk120_ct_sq
## 1  NA   6    0    0  0         0  1      4      280.8      78848.67
## 2  NA   3    0    0  0         0  1      4      466.3     217435.74
## 3  67   2    0    0  0         0  1      4      948.0     898704.00
## 4   9   1    0    0  0         0  1      4      502.3     252305.34
## 5  61   2    0    0  0         0  1      4     -134.2      18009.63
## 6  NA  NA    0    0  1         0  1      3     1816.2    3298583.15</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Je vérifie le modèle avec les termes polynomiaux</span>
modele3&lt;-<span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(milk120_ct<span class="op">+</span>milk120_ct_sq)) 
<span class="kw">summary</span>(modele3)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wpc ~ (milk120_ct + milk120_ct_sq), data = daisy2_mod)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -66.34 -38.70 -15.26  25.28 222.44 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    6.697e+01  1.639e+00  40.856   &lt;2e-16 ***
## milk120_ct    -2.545e-03  1.892e-03  -1.345   0.1787    
## milk120_ct_sq  4.089e-06  1.998e-06   2.046   0.0409 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 51.65 on 1533 degrees of freedom
##   (440 observations deleted due to missingness)
## Multiple R-squared:  0.003696,   Adjusted R-squared:  0.002396 
## F-statistic: 2.843 on 2 and 1533 DF,  p-value: 0.05854</code></pre>
<p><strong>Réponse:</strong> Oui, le terme au carré est significativement associé (i.e. <em>P</em> = 0.04) à wpc. Donc le terme représentant la courbe à un coefficient différent de 0.</p>
<p><strong>b.</strong> Selon votre analyse graphique réalisée à la question 1.a, pensez-vous que vous auriez besoin d’ajouter d’autres points d’inflexions pour bien représenter cette association? Vérifiez votre réponse en ajoutant un terme au cube pour milk120 en plus du terme au carré.</p>
<p><strong>Réponse:</strong> <em>a priori</em>, ça semblait être une simple courbe.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Je créé une variable milk120 à la puissance 3</span>
daisy2_mod<span class="op">$</span>milk120_ct_cu &lt;-daisy2_mod<span class="op">$</span>milk120_ct_sq<span class="op">*</span>daisy2_mod<span class="op">$</span>milk120_ct
<span class="co">#Je l&#39;ajoute au modèle</span>
modele4&lt;-<span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(milk120_ct<span class="op">+</span>milk120_ct_sq<span class="op">+</span>milk120_ct_cu)) 
<span class="kw">summary</span>(modele4)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wpc ~ (milk120_ct + milk120_ct_sq + milk120_ct_cu), 
##     data = daisy2_mod)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -68.71 -38.40 -15.64  25.59 223.22 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    6.724e+01  1.650e+00  40.761   &lt;2e-16 ***
## milk120_ct    -6.171e-03  3.163e-03  -1.951   0.0513 .  
## milk120_ct_sq  3.330e-06  2.067e-06   1.611   0.1073    
## milk120_ct_cu  2.651e-09  1.854e-09   1.430   0.1530    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 51.63 on 1532 degrees of freedom
##   (440 observations deleted due to missingness)
## Multiple R-squared:  0.005023,   Adjusted R-squared:  0.003075 
## F-statistic: 2.578 on 3 and 1532 DF,  p-value: 0.05222</code></pre>
<p>Effectivement, le terme au cube à <em>P</em>=0.15 (i.e. n’ajoute rien au modèle).</p>
<p><strong>c.</strong> Dans ce dernier modèle, vérifiez qu’il n’y a pas de problème sévère de colinéarité.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(car)
<span class="kw">vif</span>(modele4)</code></pre></div>
<pre><code>##    milk120_ct milk120_ct_sq milk120_ct_cu 
##      2.808468      1.074436      2.918711</code></pre>
<p><strong>Réponse:</strong> Les VIF sont tous &lt; 10, donc pas de problème.</p>
<p><strong>3)</strong> Dans le modèle suivant <span class="math inline">\(wpc = β_0 +β_1parityct + β_2twin + β_3dyst\)</span> vous vous demandez si les problèmes de vêlage (i.e. twin et dyst ensemble) apporte significativement au modèle. Quel test pourriez-vous réaliser afin de répondre à cette question? Quel est le résultat de ce test et votre interprétation de ce résultat?</p>
<p><strong>Réponse:</strong> Test de <em>F</em> pour comparer modèle complet (i.e. parity_ct, twin et dyst) vs. modèle réduit (i.e. parity_ct).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modele_complet &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(par_ct<span class="op">+</span>twin<span class="op">+</span>dyst))
modele_reduit &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(par_ct))
<span class="kw">anova</span>(modele_complet, modele_reduit)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: wpc ~ (par_ct + twin + dyst)
## Model 2: wpc ~ (par_ct)
##   Res.Df     RSS Df Sum of Sq      F  Pr(&gt;F)  
## 1   1570 4167004                              
## 2   1572 4182050 -2    -15046 2.8345 0.05905 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><em>P</em> =0.06, donc ces variables, ensemble, n’apporte pas au modèle (i.e. les coefficients de régression ne sont pas différent de 0).</p>
<p><strong>4)</strong> Recodez maintenant parity afin d’avoir une nouvelle variable catégorique (parity_cat) à 3 niveaux (parity 1, parity 2 et parity ≥3). Vérifiez la relation entre parity_cat et WPC en vous assurant d’avoir parity 1 comme valeur de référence.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Je créé une variable parity catégorique:</span>
daisy2_mod<span class="op">$</span>par_cat &lt;-<span class="st"> </span><span class="kw">cut</span>(daisy2_mod<span class="op">$</span>parity, <span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="ot">Inf</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;First&quot;</span>, <span class="st">&quot;Second&quot;</span>, <span class="st">&quot;Third or more&quot;</span>))
<span class="co">#Je fixe le niveau de référence</span>
<span class="co">#J&#39;écris le modèle</span>
daisy2_mod&lt;-<span class="kw">within</span>(daisy2_mod, par_cat&lt;-<span class="kw">relevel</span>(par_cat, <span class="dt">ref=</span><span class="st">&quot;First&quot;</span>)) <span class="co">#Sélection de la valeur de référence par_cat=1</span>
modele5 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(par_cat))
<span class="kw">summary</span>(modele5)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wpc ~ (par_cat), data = daisy2_mod)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -67.54 -38.21 -15.54  24.46 227.46 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           66.9520     2.5270  26.495   &lt;2e-16 ***
## par_catSecond          0.2592     3.6750   0.071    0.944    
## par_catThird or more   3.5895     3.1284   1.147    0.251    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 51.6 on 1571 degrees of freedom
##   (402 observations deleted due to missingness)
## Multiple R-squared:  0.001132,   Adjusted R-squared:  -0.0001392 
## F-statistic: 0.8905 on 2 and 1571 DF,  p-value: 0.4106</code></pre>
<p><strong>a.</strong> Est-ce que parity_cat (comme variable) est significativement associée à WPC?<br />
<strong>Réponse:</strong> Non, le test de <em>F</em> qui teste tous les coeffients ensemble donne <em>P</em>=0.41</p>
<p><strong>b.</strong> De combien WPC change pour une vache de 2ième parité comparativement à une vache de 1ère parité?<br />
<strong>Réponse:</strong> +0.3 jours</p>
<p><strong>c.</strong> Quel est le WPC pour une vache de 1ère parité?<br />
<strong>Réponse:</strong> 67.0 jours</p>
<p><strong>d.</strong> Quelle est la différence de WPC entre une 2ième et une 3ième parité et quel est l’IC 95% ajusté pour comparaisons multiples pour cette différence? Cette différence est-elle statistiquement significative?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(emmeans)
contrast &lt;-<span class="st"> </span><span class="kw">emmeans</span>(modele5, <span class="st">&quot;par_cat&quot;</span>) <span class="co">#Ici j&#39;ai créé un objet nommé contrast qui contient les éléments dont j&#39;aurai besoin pour comparer les catégories de par_cat</span>
<span class="kw">pairs</span>(contrast) <span class="co">#Je demande ensuite de comparer les différentes catégories. </span></code></pre></div>
<pre><code>##  contrast               estimate   SE   df t.ratio p.value
##  First - Second           -0.259 3.68 1571 -0.071  0.9973 
##  First - Third or more    -3.589 3.13 1571 -1.147  0.4850 
##  Second - Third or more   -3.330 3.24 1571 -1.027  0.5601 
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Pour voir les intervalle de confiance, je pourrais demander un confint() sur cet fonction pairs()</span>
<span class="kw">confint</span>(<span class="kw">pairs</span>(contrast))</code></pre></div>
<pre><code>##  contrast               estimate   SE   df lower.CL upper.CL
##  First - Second           -0.259 3.68 1571    -8.88     8.36
##  First - Third or more    -3.589 3.13 1571   -10.93     3.75
##  Second - Third or more   -3.330 3.24 1571   -10.94     4.28
## 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><strong>Réponse:</strong> 3.3 jours de plus pour une 3ième parité (<em>vs</em>. 2ième). <em>IC95</em>: -4.3 à 10.9 jours de plus. Ce n'est pas une différence statistiquement significative (la valeur zéro est incluse dans l'<em>IC95</em>).</p>
<p><strong>5)</strong> Vous supposez que l’effet d’une dystocie (dyst) sur WPC varie en fonction de la parité (catégorique 1ère, 2ième, ou ≥3ième). Par exemple, une vache plus vieille ayant une dystocie aura possiblement un délai plus long jusqu’à la saille fécondante comparativement à une vache plus jeune.</p>
<p><strong>a.</strong> Que devrez-vous tester pour vérifier cette hypothèse?<br />
<strong>Réponse:</strong> L'interaction entre <em>dyst</em> et <em>par_cat</em>.</p>
<p><strong>b.</strong> Effectuer ce test. Est-ce que l’effet de dystocie varie de manière statistiquement significative en fonction de la parité?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modele6 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(par_cat<span class="op">*</span>dyst))
<span class="kw">summary</span>(modele6)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wpc ~ (par_cat * dyst), data = daisy2_mod)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -84.00 -37.65 -15.47  24.53 228.35 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                67.0249     2.7110  24.724   &lt;2e-16 ***
## par_catSecond               0.4429     3.8446   0.115   0.9083    
## par_catThird or more        2.6221     3.2911   0.797   0.4257    
## dyst                       -0.5428     7.3977  -0.073   0.9415    
## par_catSecond:dyst         -5.1015    14.7724  -0.345   0.7299    
## par_catThird or more:dyst  33.8958    13.5848   2.495   0.0127 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 51.51 on 1568 degrees of freedom
##   (402 observations deleted due to missingness)
## Multiple R-squared:  0.006688,   Adjusted R-squared:  0.00352 
## F-statistic: 2.111 on 5 and 1568 DF,  p-value: 0.0615</code></pre>
<p><strong>Réponse:</strong> Notez que j'ai maintenant 2 coefficients (<em>par_catSecond:dyst</em> et <em>par_catThird or more:dyst</em>) qui, ensemble, représente l'interaction entre <em>par_cat</em> et <em>dyst</em>. Je dois donc faire un test de <em>F</em> sur ces 2 coefficients à la fois.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Le modèle réduit sans les deux coefficients:</span>
modele_red &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>daisy2_mod, wpc <span class="op">~</span><span class="st"> </span>(par_cat<span class="op">+</span>dyst))
<span class="co">#La fonction anova() pour comparer les modèles:</span>
<span class="kw">anova</span>(modele6, modele_red)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: wpc ~ (par_cat * dyst)
## Model 2: wpc ~ (par_cat + dyst)
##   Res.Df     RSS Df Sum of Sq      F  Pr(&gt;F)  
## 1   1568 4160082                              
## 2   1570 4179615 -2    -19533 3.6812 0.02541 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Oui l'interaction est significative, j'obtiens une valeur de <em>P</em>=0.03 pour le test de <em>F</em>.</p>
<p><strong>c.</strong> Quel est le nombre de jours moyen jusqu’à la saillie fécondante pour chacune des catégories de parité et de dystocie (i.e. remplir le tableau suivant)? Pour quel niveau de parité les différences semblent les plus importantes?</p>
<table>
<caption><span id="tab:unnamed-chunk-54">Table 7.2: </span>Nombre moyen estimé de jours jusqu’à la saillie fécondante pour chacune des catégories de parité et de dystocie</caption>
<thead>
<tr class="header">
<th align="left">Parite</th>
<th align="left">Dystocie_0</th>
<th align="left">Dystocie_1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1ère lactation</td>
<td align="left">67.0 jours</td>
<td align="left">67.0-0.5=66.5 jours</td>
</tr>
<tr class="even">
<td align="left">2ième lactation</td>
<td align="left">67.0+0.4=67.4 jours</td>
<td align="left">67.0+0.4-0.5-5.1=61.8 jours</td>
</tr>
<tr class="odd">
<td align="left">3ième ou plus</td>
<td align="left">67.0+2.6=69.6 jours</td>
<td align="left">67.0+2.6-0.5+33.9=103.0 jours</td>
</tr>
</tbody>
</table>

</div>
</div>









            </section>

          </div>
        </div>
      </div>
<a href="régression-linéaire.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labo R Bookdown project.pdf", "Labo R Bookdown project.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
